// lib/dailyThoughts.js
// Pre-generated "Gând al zilei" (Thought of the Day) bank
// ~30 thoughts per HD type × 5 types × 10 languages
// Zero API cost — platform selects randomly from the bank
// No repeat in the same month (30 thoughts = 1 per day)
// Alex validates RO as quality standard

const DAILY_THOUGHTS = {
  en: {
    Generator: [
      { title: "Your yes matters", body: "Not every opportunity deserves your energy. The ones that light you up — those are the ones worth your time. Today, notice what makes your body say yes.", question: "What made you feel most alive this week?" },
      { title: "Frustration is a compass", body: "When you feel frustrated, it usually means you are spending energy on something that is not yours to do. Frustration is not failure — it is feedback.", question: "Where is frustration trying to redirect you?" },
      { title: "Built to build", body: "You have more sustained energy than most people. But only when you are doing work that genuinely excites you. The moment it becomes obligation, the energy drains.", question: "What are you building right now that actually excites you?" },
      { title: "Mastery takes patience", body: "You are designed to go deep, not wide. The things you master over time become your greatest strengths. Trust the process of repetition.", question: "What skill are you developing through repetition?" },
      { title: "Wait, then respond", body: "Your strategy is not to chase — it is to respond. Life brings opportunities to your door. Your job is to be present enough to notice them.", question: "What showed up recently that you almost missed?" },
      { title: "Satisfaction is your signal", body: "When you feel satisfied at the end of a day, you know you spent your energy right. When you feel drained, something was off.", question: "How satisfied did you feel at the end of yesterday?" },
      { title: "Your body knows", body: "Your gut response is faster and more accurate than your mind. When something is right for you, your body moves toward it before your brain catches up.", question: "What is your body telling you right now?" },
      { title: "Energy is not infinite", body: "Even with your sustainable energy, you need to refuel. Sleep, movement, and doing what you love are not luxuries — they are fuel.", question: "How are you refueling today?" },
      { title: "Not everything is yours", body: "Just because you can do something does not mean you should. Saying no to the wrong things protects your energy for the right things.", question: "What should you say no to this week?" },
      { title: "Respond, don't react", body: "There is a difference between responding and reacting. Responding comes from your center. Reacting comes from pressure. Pause before you move.", question: "Where did you react instead of respond recently?" },
      { title: "The work that works you", body: "When the work is right, it works you as much as you work it. You lose track of time. You feel energized, not drained. That is the signal.", question: "When did time disappear for you recently?" },
      { title: "Sustainable, not explosive", body: "Your energy is a marathon, not a sprint. You do not need to burn bright and fast. You need to burn steady and long.", question: "Are you pacing yourself or burning out?" },
      { title: "Follow the pull", body: "Something is pulling your attention today. It might be subtle. It might be a conversation, an idea, a project. Follow it — that is your sacral responding.", question: "What is pulling your attention right now?" },
      { title: "Your frustration is valid", body: "Feeling frustrated does not make you difficult. It makes you honest. You know when something is not right — trust that knowing.", question: "What frustration have you been ignoring?" },
      { title: "Let it come to you", body: "The best things in your life probably came when you were not looking for them. Trust that pattern. Stop chasing. Start noticing.", question: "What came to you recently without you chasing it?" },
      { title: "Depth over breadth", body: "You do not need to do everything. You need to do the right things deeply. One project done with love beats five done with obligation.", question: "What deserves your full depth right now?" },
      { title: "Morning energy", body: "How you start your morning sets the tone for your whole day. Not with productivity hacks — with presence. Feel your body before you check your phone.", question: "How did you start this morning?" },
      { title: "The right people", body: "You thrive around people who value what you build. Not everyone will. That is not your problem — it is information about where to invest your energy.", question: "Who values what you create?" },
      { title: "Your definition of enough", body: "The world will always ask for more. Your job is to know when you have given enough. Not from guilt — from self-knowledge.", question: "Where do you need to say 'enough' today?" },
      { title: "Rest is productive", body: "For you, rest is not the absence of work. It is what makes good work possible. Do not feel guilty about recharging — feel guilty about not doing it.", question: "When did you last truly rest?" },
      { title: "Magnetic, not pushy", body: "When you are doing what you love, people are drawn to you naturally. You do not need to sell yourself. You need to be yourself.", question: "Where are you trying too hard to be seen?" },
      { title: "What lights up stays", body: "Pay attention to what consistently lights you up. Not what you think should light you up. Not what others say. What actually does.", question: "What has consistently lit you up over the years?" },
      { title: "The sacral sound", body: "Your most honest answers come from sounds, not words. A deep yes. A flat no. Practice listening to your body before your mind speaks.", question: "What did your body say yes to today?" },
      { title: "You are not lazy", body: "If you feel unmotivated, it is not because you are lazy. It is because you are spending energy on the wrong things. Find what excites you.", question: "What would excite you if you gave yourself permission?" },
      { title: "Build what matters", body: "You are here to build things that last. Not to please everyone. Not to keep busy. To create something real and meaningful.", question: "What are you building that will last?" },
      { title: "The gap between knowing and doing", body: "You know more than you act on. Today, close one gap. Do one thing you have been knowing you should do.", question: "What have you been knowing but not doing?" },
      { title: "Your energy is your gift", body: "The energy you bring to a room, a project, a relationship — that is your gift. Protect it. Direct it. Do not waste it on things that do not matter.", question: "Where is your energy going that does not serve you?" },
      { title: "Celebrate the process", body: "You are in process. That is not a problem — that is life working through you. Celebrate where you are, not just where you want to be.", question: "What progress can you celebrate today?" },
      { title: "Evening reflection", body: "Before you sleep, ask yourself one thing: did I spend my energy on what matters? No judgment. Just observation.", question: "Did your energy go where it mattered today?" },
      { title: "Tomorrow is a response", body: "Tomorrow will bring new things to respond to. You do not need to plan everything. You need to show up present and trust your response.", question: "What are you looking forward to responding to?" },
    ],
    'Manifesting Generator': [
      { title: "Your speed is a gift", body: "You move faster than most people. That is not impatience — it is efficiency. You see shortcuts others miss. Trust your pace.", question: "Where did your speed serve you recently?" },
      { title: "Inform, then move", body: "The people around you need to know what you are about to do. Not for permission — for clarity. Inform, then move. It prevents friction.", question: "Who do you need to inform today?" },
      { title: "Multiple passions are valid", body: "You are not scattered. You are multi-passionate. The world rewards specialists, but you are built for variety. That is your design.", question: "What variety are you craving right now?" },
      { title: "The skip is the shortcut", body: "You skip steps. Not because you are careless, but because you intuitively know which steps matter and which are filler. Trust that instinct.", question: "What step did you skip recently that turned out fine?" },
      { title: "Frustration plus anger", body: "When you feel frustrated and angry at the same time, you are probably forcing yourself to do something that no longer excites you. Time to pivot.", question: "What are you doing that no longer excites you?" },
      { title: "Pivot without guilt", body: "Changing direction is not quitting. It is recalibrating. You need freedom to follow what lights you up — even if others do not understand.", question: "What do you need to pivot away from?" },
      { title: "Your energy is contagious", body: "When you are excited, everyone around you feels it. That enthusiasm is not naive — it is your superpower. Use it deliberately.", question: "What are you genuinely enthusiastic about right now?" },
      { title: "Wait for the spark", body: "You still need to wait for something to respond to before you move. The difference is that once you respond, you move fast. Trust the wait.", question: "What sparked your response recently?" },
      { title: "Not everything at once", body: "You can handle many things, but not everything at once. Choose what excites you most today and give it your best energy.", question: "What deserves your best energy today?" },
      { title: "Let yourself be surprised", body: "Some of your best work happens when you did not plan it. Leave space for spontaneity — that is where your magic lives.", question: "When did spontaneity lead to something great?" },
      { title: "The power of variety", body: "Doing the same thing every day kills your energy. Build variety into your routine — different tasks, different environments, different people.", question: "What variety will you add to your day?" },
      { title: "Your body leads", body: "Your sacral response tells you what is right. Your throat tells you what to communicate. Let your body lead and your mind follow.", question: "What is your body leading you toward?" },
      { title: "Fast does not mean reckless", body: "Moving fast is your nature. But speed with awareness is different from speed without awareness. Stay present even when you move quickly.", question: "Where can you slow down just enough to stay present?" },
      { title: "Satisfaction and peace", body: "Your signature is both satisfaction and peace. When both are present, you know you are on track. When one is missing, pay attention.", question: "Do you feel both satisfaction and peace right now?" },
      { title: "Multi-tracking", body: "Having three projects at once is not a disorder. It is how you are designed. The key is that all three genuinely excite you.", question: "Are your current projects still exciting?" },
      { title: "Communicate your changes", body: "When you pivot, tell people. Not to ask permission — to maintain trust. People can handle your changes if they understand them.", question: "Who needs to hear about a change you are making?" },
      { title: "Rest between bursts", body: "You work in powerful bursts. Between those bursts, you need genuine rest. Not scrolling. Not planning. Actual rest.", question: "Are you resting between your bursts?" },
      { title: "Trust your shortcuts", body: "Your mind finds the efficient path naturally. Others may not understand why you skipped from A to D, but you know it works.", question: "What shortcut is your mind showing you right now?" },
      { title: "The right kind of busy", body: "Being busy is not the same as being productive. You need the right kind of busy — the kind that leaves you satisfied, not just tired.", question: "Is your busyness leaving you satisfied or just tired?" },
      { title: "Energy management", body: "Your energy is powerful but not unlimited. Today, notice what adds to your energy and what subtracts from it. Adjust accordingly.", question: "What added energy to your day? What subtracted?" },
      { title: "Follow excitement", body: "Excitement is your compass. Not logic, not obligation, not what others expect. When something excites you, that is your body saying yes.", question: "What excites you that you have been putting off?" },
      { title: "Your pace is your own", body: "Some days you move at lightning speed. Some days you need to slow down. Both are valid. Do not force a pace that is not natural today.", question: "What pace feels right for today?" },
      { title: "Not quitting, evolving", body: "When you drop something, it is not always quitting. Sometimes it is evolving. You outgrow things faster than most people — that is normal for you.", question: "What have you outgrown?" },
      { title: "The juggle", body: "You juggle well. But even good jugglers need to put some balls down sometimes. What can you set down today without guilt?", question: "What can you set down today?" },
      { title: "Morning spark", body: "The first thing that excites you in the morning is often the most important thing to act on. Before the to-do list takes over, follow the spark.", question: "What was the first thing that excited you this morning?" },
      { title: "Your contribution", body: "You bring energy and momentum to everything you touch. Teams need your spark. Projects need your speed. Own that contribution.", question: "Where is your energy making the biggest impact?" },
      { title: "Patience with yourself", body: "You expect a lot from yourself because you know what you are capable of. But even you need patience. Growth is not always fast.", question: "Where do you need more patience with yourself?" },
      { title: "Tonight, check in", body: "Before sleep, ask yourself: did I follow my excitement today? Did I inform before I moved? Did I rest between bursts?", question: "Did you follow your excitement today?" },
      { title: "Tomorrow brings options", body: "Tomorrow will bring new things to respond to. You do not need to have it all figured out tonight. Trust that your response will be clear.", question: "What option are you looking forward to exploring?" },
      { title: "The dance of doing", body: "Your life is a dance between doing and being. Today, notice which one you need more of. Both serve you — in the right moment.", question: "Do you need more doing or more being today?" },
    ],
    Manifestor: [
      { title: "You are the beginning", body: "You start things. That is your gift. You do not need permission to begin — you need to inform the people around you that you are about to.", question: "What are you ready to start?" },
      { title: "Inform, not ask", body: "Informing is not asking for permission. It is giving others a chance to prepare for what you are about to set in motion.", question: "Who would benefit from knowing your next move?" },
      { title: "Peace is your compass", body: "When you feel at peace, you are on track. When you feel angry, something or someone is trying to control you. Pay attention.", question: "Where is anger trying to tell you something?" },
      { title: "Impact is inevitable", body: "Everything you do has an impact on the people around you. Not because you try to — because that is how your energy works. Own it.", question: "What impact did you have today that you did not intend?" },
      { title: "Rest after initiation", body: "You move in powerful bursts. After each initiation, you need real rest. Not guilt about resting — actual, unapologetic rest.", question: "Are you resting enough between your initiations?" },
      { title: "Your independence matters", body: "You do your best work alone or on your own terms. That is not antisocial — it is how you are designed. Protect your independence.", question: "What independence do you need to protect today?" },
      { title: "Not everyone will understand", body: "You move differently than most people. Not everyone will understand your pace, your independence, your need for autonomy. That is okay.", question: "Whose opinion are you carrying that you should put down?" },
      { title: "The urge to create", body: "When you feel the urge to create something, do not overthink it. Inform the relevant people, then move. Hesitation kills your energy.", question: "What creative urge have you been sitting on?" },
      { title: "Anger as information", body: "Your anger is not a character flaw. It is information that your freedom is being compromised. Listen to it, then act on the information.", question: "What is your anger telling you this week?" },
      { title: "You do not need a team", body: "You can do remarkable things alone. Teams can help, but only if they do not slow you down or try to control your process.", question: "Where would working alone serve you better?" },
      { title: "Initiate with intention", body: "Before you start something, be clear about why. Your initiations have power — direct them toward what truly matters to you.", question: "Is your current initiative aligned with what matters most?" },
      { title: "Let go of control", body: "You initiate, but you do not need to control the outcome. Start things, inform people, then let go and let it unfold.", question: "What outcome are you trying to control?" },
      { title: "Your energy is closed", body: "Your energy field pushes outward. People feel your presence before you speak. This is powerful — and it can intimidate. Be aware of both.", question: "How does your presence affect the people around you?" },
      { title: "Solitude is fuel", body: "Time alone is not loneliness for you — it is recharging. You need solitude the way Generators need engagement. Do not apologize for it.", question: "When did you last have quality solitude?" },
      { title: "Inform to connect", body: "Informing is how you build trust. When people know what you are doing and why, they support you instead of resisting you.", question: "Who in your life would benefit from more information from you?" },
      { title: "Morning clarity", body: "The morning is often when your creative impulses are strongest. Before the world demands your attention, check in with your own urges.", question: "What impulse showed up this morning?" },
      { title: "Boundaries are not walls", body: "You set strong boundaries. That does not make you cold — it makes you clear. Clear people attract clear relationships.", question: "What boundary do you need to reinforce?" },
      { title: "Your rhythm", body: "You do not work on a 9-to-5 schedule. You work in bursts of intense creation followed by rest. Honor that rhythm instead of fighting it.", question: "Is your current schedule honoring your natural rhythm?" },
      { title: "The courage to begin", body: "Starting something new takes courage. You have that courage built in. Today, remember that the world needs people who begin things.", question: "What would you begin if you had no fear?" },
      { title: "Tonight, review your impact", body: "Before sleep, reflect on the impact you had today. Not good or bad — just impact. Awareness is the first step to directing it well.", question: "What was your biggest impact today?" },
      { title: "You set the pace", body: "In any room, in any project, you naturally set the pace. Others follow your lead. Be intentional about where you lead people.", question: "Where are you leading people right now?" },
      { title: "Not broken, designed", body: "If people have told you you are too intense, too independent, or too much — that is their discomfort, not your design flaw.", question: "What part of yourself have you been told to tone down?" },
      { title: "Create first, optimize later", body: "You are built to start things, not perfect them. Get it moving, then hand off the details to someone who thrives on them.", question: "What have you been perfecting instead of starting something new?" },
      { title: "Your fire", body: "You carry an internal fire that most people do not have. It needs expression, not suppression. Find what lets it burn today.", question: "What is your fire asking for today?" },
      { title: "Patience with the world", body: "The world moves slower than you. That is not the world's fault or yours. Patience is not weakness — it is strategic awareness.", question: "Where do you need patience with the world right now?" },
      { title: "Initiation as service", body: "When you start something meaningful, you create possibilities for others too. Your initiations ripple outward. That is service, not selfishness.", question: "What have you started that opened doors for others?" },
      { title: "The anger test", body: "If you have not felt angry in a while, you might be suppressing your true impulses. Healthy anger means you are still connected to what matters.", question: "What are you suppressing to keep the peace?" },
      { title: "Tomorrow you begin again", body: "Every day is a new chance to initiate something. You do not carry yesterday's momentum — you create today's. Wake up ready to begin.", question: "What will you begin tomorrow?" },
    ],
    Projector: [
      { title: "Wait for the invitation", body: "The right opportunities come with recognition. When someone truly sees your value and invites you in, that is your opening. Before that, patience.", question: "Where are you waiting for an invitation right now?" },
      { title: "Your energy is focused", body: "You do not have the same energy as Generators. Your power is in focused bursts, not sustained output. Work smart, rest often.", question: "How did you manage your energy today?" },
      { title: "Recognition matters", body: "You need to be seen for who you are, not just what you do. When recognition comes, it fuels you. When it does not, rest and refocus.", question: "Who truly sees you?" },
      { title: "Guide, don't do", body: "You are not here to do all the work yourself. You are here to see, understand, and guide. Let others handle the execution.", question: "Where are you doing too much yourself?" },
      { title: "Bitterness is a signal", body: "When you feel bitter, it means you are overworking and under-recognized. That is not self-pity — it is your system telling you to recalibrate.", question: "Where is bitterness showing up?" },
      { title: "Quality over quantity", body: "You are built for depth, not volume. One deeply understood insight is worth more than ten surface-level observations.", question: "What insight have you been sitting with?" },
      { title: "Rest is not optional", body: "Rest is not lazy for you — it is essential. Without regular rest, your focus deteriorates and bitterness grows. Treat rest as part of your work.", question: "Did you build rest into your day?" },
      { title: "Your perception is your gift", body: "You see things others miss. Patterns in people, systems, relationships. That perception is valuable — but only when invited.", question: "What have you noticed that no one asked about?" },
      { title: "The right environment", body: "You are sensitive to your environment. The wrong space drains you. The right space energizes you. Choose your environments deliberately.", question: "Is your current environment supporting you?" },
      { title: "Success is your signature", body: "When you are living correctly — waiting for invitations, resting, sharing your wisdom when asked — you feel success. That feeling is your compass.", question: "Where do you feel successful right now?" },
      { title: "Not everyone deserves your guidance", body: "Your wisdom is precious. Do not give it away to people who did not ask for it. Save your energy for those who truly want your perspective.", question: "Who truly wants your guidance?" },
      { title: "Study what interests you", body: "You are a natural student. The things you study become the foundation of the wisdom you eventually share. Never stop learning.", question: "What are you studying right now?" },
      { title: "Your pace is different", body: "You work differently than the world expects. Shorter hours, deeper focus, more rest. That is not weakness — it is your design working correctly.", question: "Are you honoring your natural pace?" },
      { title: "Boundaries with energy vampires", body: "People absorb your focused energy. Without boundaries, you end up depleted by others' chaos. Protect your energy deliberately.", question: "Who is draining your energy?" },
      { title: "The invitation will come", body: "If you are doing your work — learning, resting, being yourself — the right invitations will find you. Trust the timing.", question: "What invitation are you hoping for?" },
      { title: "Morning rest check", body: "Before you start your day, check in: am I rested enough? If not, adjust your plan. An unrested Projector is an ineffective one.", question: "How rested do you feel this morning?" },
      { title: "See the system", body: "You have a gift for seeing how systems work — teams, organizations, relationships. Today, use that gift for yourself: look at your own patterns.", question: "What pattern are you running on autopilot?" },
      { title: "Wisdom takes time", body: "Your best insights come after processing, not in the moment. Give yourself time to think before you share. Marinated wisdom lands deeper.", question: "What needs more time to process before you share it?" },
      { title: "Less is more", body: "For you, doing less often produces more. One focused hour beats four scattered ones. One right word beats a monologue.", question: "Where can you do less and produce more?" },
      { title: "Tonight, feel your success", body: "Before bed, find one moment from today where you felt successful. Not productive — successful. There is a difference.", question: "What felt like genuine success today?" },
      { title: "Patience is power", body: "Waiting is not passive for you — it is powerful. Every moment you wait for the right invitation, you are building energy for when it arrives.", question: "What are you building energy for?" },
      { title: "You are not broken", body: "If you cannot keep up with Generator pace, you are not broken. You are designed differently. Your power is in precision, not endurance.", question: "Where have you been comparing yourself to Generators?" },
      { title: "Selective yes", body: "Every yes costs you energy. Be selective. The right yes opens doors. The wrong yes closes them by depleting you.", question: "What should you have said no to recently?" },
      { title: "Your value is inherent", body: "You do not need to prove your worth through overwork. Your value is in who you are and how you see the world. That is enough.", question: "Where are you trying to prove your worth?" },
      { title: "The nap is a strategy", body: "A midday rest is not weakness — it is strategic. Your energy renews through rest, not through pushing harder. Take the nap.", question: "Can you build a short rest into today?" },
    ],
    Reflector: [
      { title: "Your environment is everything", body: "You absorb the energy of every space you enter. The right environment makes you thrive. The wrong one makes you wilt. Choose carefully.", question: "How does your current environment feel?" },
      { title: "You are the mirror", body: "You reflect the health of the community around you. When the community is thriving, you feel it. When it is struggling, you feel that too.", question: "What is your community reflecting right now?" },
      { title: "Give it a month", body: "Big decisions need a full lunar cycle. Not because you are indecisive — because your clarity comes slowly and thoroughly. Trust your process.", question: "What decision are you giving time to?" },
      { title: "Surprise is your compass", body: "When you feel surprised and delighted, you are on track. When you feel disappointed, something around you needs attention.", question: "What surprised you recently in a good way?" },
      { title: "You are rare", body: "Only about 1% of people share your design. That makes you unusual — and unusually valuable. Your perspective matters because it is so different.", question: "What perspective do you bring that others miss?" },
      { title: "Fluid identity is normal", body: "You feel different depending on who you are with. That is not instability — it is your design. You are meant to sample, not to be fixed.", question: "Who have you been with recently that felt right?" },
      { title: "Protect your sensitivity", body: "Your sensitivity is your superpower, not your weakness. But it needs protection. Noise, chaos, and negativity affect you more than most.", question: "What are you protecting yourself from today?" },
      { title: "Disappointment tells the truth", body: "When you feel disappointed, your environment or community is not living up to its potential. That is important information — not just emotion.", question: "What is disappointing you right now?" },
      { title: "Talk to many people", body: "When making a decision, talk to different people about it. Each conversation reveals a new angle. After a month of conversations, clarity appears.", question: "Who should you talk to about your current decision?" },
      { title: "The right people matter most", body: "More than any other type, you depend on the quality of people around you. Choose your inner circle with extreme care.", question: "Who is in your inner circle — and should they be?" },
      { title: "Not everyone's energy is yours", body: "Today, notice when you are feeling something that is not yours. The anxiety, the excitement, the sadness — it might belong to someone nearby.", question: "What emotion are you carrying that might not be yours?" },
      { title: "Slow decisions are strong decisions", body: "Your decisions get stronger with time, not weaker. Quick decisions are for other types. Your power is in patience and thoroughness.", question: "What decision improved by waiting?" },
      { title: "The moon and you", body: "Your energy shifts with the lunar cycle. Some weeks you feel clear and strong. Other weeks, foggy and uncertain. Both are normal for you.", question: "Where are you in your energy cycle right now?" },
      { title: "Space to be yourself", body: "You need regular time alone — not to be lonely, but to figure out what is yours versus what you absorbed from others.", question: "When did you last spend quality time alone?" },
      { title: "You see the truth", body: "Because you reflect what is around you, you often see the truth of a situation before anyone else does. Trust what you see.", question: "What truth are you seeing that others are not?" },
      { title: "Environmental audit", body: "Today, pay attention to how different spaces make you feel. The office, the café, your home. Your body is telling you where you belong.", question: "Where did you feel best today?" },
      { title: "Change is not betrayal", body: "You change based on who you are with and where you are. That is not being fake — it is being responsive. Honor your fluidity.", question: "How did you change today based on your environment?" },
      { title: "Community health check", body: "You are the canary in the coal mine for your community. If you feel off, something in the collective might be off too.", question: "What is the health of your community right now?" },
      { title: "Wait with intention", body: "Waiting is not passive for you. It is active gathering — of information, perspectives, feelings. You are processing more than you realize.", question: "What are you actively processing right now?" },
      { title: "Tonight, release what is not yours", body: "Before sleep, consciously release the energies you absorbed today. Not everything you felt was yours. Let it go and return to yourself.", question: "What can you release before sleep?" },
      { title: "Your rarity is your strength", body: "Being so different from everyone else can feel lonely. But your rarity gives you a perspective no one else has. That is a gift.", question: "What gift does your uniqueness give you?" },
      { title: "Patience with your clarity", body: "Clarity will come. It always does. But it comes on its own schedule, not when you demand it. Be patient with your process.", question: "What are you waiting for clarity on?" },
      { title: "The sampling life", body: "You are designed to taste different experiences, not commit to one flavor forever. Give yourself permission to explore.", question: "What new experience are you curious about?" },
      { title: "Your presence matters", body: "Sometimes the most important thing you do is simply be present. Your presence changes the energy of a room — for the better.", question: "Where does your presence matter most?" },
      { title: "Morning environment check", body: "How does the first space you enter in the morning feel? If it does not feel good, adjust it. Your morning environment sets your entire day.", question: "How does your morning environment feel?" },
    ],
  },

  ro: {
    Generator: [
      { title: "Da-ul tău contează", body: "Nu fiecare oportunitate merită energia ta. Cele care te aprind — alea merită timpul tău. Azi, observă ce face corpul tău să spună da.", question: "Ce te-a făcut să te simți cel mai viu săptămâna asta?" },
      { title: "Frustrarea e o busolă", body: "Când te simți frustrat, de obicei înseamnă că îți cheltuiești energia pe ceva ce nu e al tău de făcut. Frustrarea nu e eșec — e feedback.", question: "Unde încearcă frustrarea să te redirecționeze?" },
      { title: "Construit să construiești", body: "Ai mai multă energie sustenabilă decât majoritatea oamenilor. Dar doar când faci ce te entuziasmează cu adevărat.", question: "Ce construiești acum care chiar te entuziasmează?" },
      { title: "Maestria cere răbdare", body: "Ești proiectat să mergi în profunzime, nu în lățime. Lucrurile pe care le stăpânești în timp devin cele mai mari forțe ale tale.", question: "Ce abilitate dezvolți prin repetiție?" },
      { title: "Așteaptă, apoi răspunde", body: "Strategia ta nu e să alergi — e să răspunzi. Viața aduce oportunități la ușa ta. Treaba ta e să fii suficient de prezent să le observi.", question: "Ce a apărut recent și aproape ai ratat?" },
      { title: "Satisfacția e semnalul tău", body: "Când te simți satisfăcut la sfârșitul unei zile, știi că ți-ai cheltuit energia corect. Când te simți golit, ceva a fost greșit.", question: "Cât de satisfăcut te-ai simțit la sfârșitul zilei de ieri?" },
      { title: "Corpul tău știe", body: "Răspunsul tău instinctiv e mai rapid și mai precis decât mintea. Când ceva e corect pentru tine, corpul se mișcă spre el înainte ca mintea să prindă din urmă.", question: "Ce îți spune corpul tău chiar acum?" },
      { title: "Energia nu e infinită", body: "Chiar și cu energia ta sustenabilă, trebuie să te realimentezi. Somnul, mișcarea și ceea ce iubești nu sunt luxuri — sunt combustibil.", question: "Cum te realimentezi azi?" },
      { title: "Nu totul e al tău", body: "Doar pentru că poți face ceva nu înseamnă că ar trebui. A spune nu lucrurilor greșite îți protejează energia pentru cele corecte.", question: "La ce ar trebui să spui nu săptămâna asta?" },
      { title: "Răspunde, nu reacționa", body: "E o diferență între a răspunde și a reacționa. Răspunsul vine din centrul tău. Reacția vine din presiune. Pauză înainte să te miști.", question: "Unde ai reacționat în loc să răspunzi recent?" },
      { title: "Munca care te lucrează", body: "Când munca e cea potrivită, ea te lucrează pe tine la fel de mult cât o lucrezi tu. Pierzi noțiunea timpului. Te simți energizat, nu golit.", question: "Când a dispărut timpul pentru tine recent?" },
      { title: "Sustenabil, nu exploziv", body: "Energia ta e un maraton, nu un sprint. Nu trebuie să arzi intens și rapid. Trebuie să arzi constant și pe termen lung.", question: "Te dozezi sau te epuizezi?" },
      { title: "Urmează atracția", body: "Ceva îți atrage atenția azi. Poate e subtil. Poate e o conversație, o idee, un proiect. Urmează-l — asta e sacralul tău care răspunde.", question: "Ce îți atrage atenția chiar acum?" },
      { title: "Frustrarea ta e validă", body: "Să te simți frustrat nu te face dificil. Te face onest. Știi când ceva nu e în regulă — ai încredere în acea cunoaștere.", question: "Ce frustrare ai ignorat?" },
      { title: "Lasă să vină la tine", body: "Cele mai bune lucruri din viața ta probabil au venit când nu le căutai. Ai încredere în acel tipar. Nu mai alerga. Începe să observi.", question: "Ce a venit la tine recent fără să alergi după?" },
      { title: "Profunzime peste lățime", body: "Nu trebuie să faci totul. Trebuie să faci lucrurile corecte în profunzime. Un proiect făcut cu dragoste bate cinci făcute din obligație.", question: "Ce merită toată profunzimea ta acum?" },
      { title: "Energia de dimineață", body: "Cum începi dimineața setează tonul pentru toată ziua. Nu cu hack-uri de productivitate — cu prezență. Simte-ți corpul înainte să verifici telefonul.", question: "Cum ai început dimineața asta?" },
      { title: "Oamenii potriviți", body: "Prosperi în jurul oamenilor care prețuiesc ce construiești. Nu toți vor face asta. Nu e problema ta — e informație despre unde să investești energia.", question: "Cine prețuiește ce creezi?" },
      { title: "Definiția ta de suficient", body: "Lumea va cere mereu mai mult. Treaba ta e să știi când ai dat suficient. Nu din vinovăție — din autocunoaștere.", question: "Unde trebuie să spui 'suficient' azi?" },
      { title: "Odihna e productivă", body: "Pentru tine, odihna nu e absența muncii. E ceea ce face munca bună posibilă. Nu te simți vinovat că te reîncarci.", question: "Când te-ai odihnit cu adevărat ultima dată?" },
      { title: "Magnetic, nu insistent", body: "Când faci ce iubești, oamenii sunt atrași de tine natural. Nu trebuie să te vinzi. Trebuie să fii tu.", question: "Unde te străduiești prea mult să fii văzut?" },
      { title: "Ce te aprinde rămâne", body: "Fii atent la ce te aprinde constant. Nu ce crezi că ar trebui să te aprindă. Nu ce spun alții. Ce chiar o face.", question: "Ce te-a aprins constant de-a lungul anilor?" },
      { title: "Sunetul sacral", body: "Cele mai oneste răspunsuri ale tale vin din sunete, nu din cuvinte. Un da profund. Un nu plat. Practică ascultarea corpului înainte să vorbească mintea.", question: "La ce a spus corpul tău da azi?" },
      { title: "Nu ești leneș", body: "Dacă te simți nemotivat, nu e pentru că ești leneș. E pentru că îți cheltuiești energia pe lucrurile greșite. Găsește ce te entuziasmează.", question: "Ce te-ar entuziasma dacă ți-ai da permisiunea?" },
      { title: "Construiește ce contează", body: "Ești aici să construiești lucruri care durează. Nu să mulțumești pe toată lumea. Nu să fii ocupat. Să creezi ceva real și semnificativ.", question: "Ce construiești care va dura?" },
      { title: "Golul dintre a ști și a face", body: "Știi mai mult decât acționezi. Azi, închide un gol. Fă un lucru pe care știi că ar trebui să-l faci.", question: "Ce ai știut dar nu ai făcut?" },
      { title: "Energia ta e darul tău", body: "Energia pe care o aduci într-o cameră, un proiect, o relație — asta e darul tău. Protejează-l. Direcționează-l.", question: "Unde se duce energia ta care nu te servește?" },
      { title: "Celebrează procesul", body: "Ești în proces. Asta nu e o problemă — e viața lucrând prin tine. Celebrează unde ești, nu doar unde vrei să fii.", question: "Ce progres poți celebra azi?" },
      { title: "Reflecție de seară", body: "Înainte să adormi, întreabă-te un singur lucru: mi-am cheltuit energia pe ce contează? Fără judecată. Doar observație.", question: "Energia ta a mers unde a contat azi?" },
      { title: "Mâine e un răspuns", body: "Mâine va aduce lucruri noi la care să răspunzi. Nu trebuie să planifici totul. Trebuie să te prezinți prezent și să ai încredere în răspunsul tău.", question: "La ce aștepți cu nerăbdare să răspunzi?" },
    ],
    'Manifesting Generator': [
      { title: "Viteza ta e un dar", body: "Te miști mai repede decât majoritatea. Nu e nerăbdare — e eficiență. Vezi scurtături pe care alții le ratează. Ai încredere în ritmul tău.", question: "Unde te-a servit viteza ta recent?" },
      { title: "Informează, apoi mișcă-te", body: "Oamenii din jurul tău trebuie să știe ce urmează să faci. Nu pentru permisiune — pentru claritate. Informează, apoi mișcă-te.", question: "Pe cine trebuie să informezi azi?" },
      { title: "Pasiunile multiple sunt valide", body: "Nu ești împrăștiat. Ești multi-pasional. Lumea recompensează specialiștii, dar tu ești proiectat pentru varietate.", question: "Ce varietate tânjești acum?" },
      { title: "Săritul e scurtătura", body: "Sari pași. Nu pentru că ești neglijent, ci pentru că intuitiv știi care pași contează și care sunt umpluturi.", question: "Ce pas ai sărit recent și a ieșit bine?" },
      { title: "Frustrare plus furie", body: "Când simți frustrare și furie în același timp, probabil te forțezi să faci ceva care nu te mai entuziasmează. E timpul să pivotezi.", question: "Ce faci care nu te mai entuziasmează?" },
      { title: "Pivotează fără vinovăție", body: "A schimba direcția nu e a renunța. E a recalibra. Ai nevoie de libertate să urmezi ce te aprinde.", question: "De la ce trebuie să pivotezi?" },
      { title: "Energia ta e contagioasă", body: "Când ești entuziasmat, toți din jurul tău simt. Acel entuziasm nu e naiv — e superputerea ta.", question: "De ce ești genuinamente entuziasmat acum?" },
      { title: "Așteaptă scânteia", body: "Tot trebuie să aștepți ceva la care să răspunzi înainte să te miști. Diferența e că odată ce răspunzi, te miști rapid.", question: "Ce ți-a declanșat răspunsul recent?" },
      { title: "Nu totul odată", body: "Poți gestiona multe lucruri, dar nu totul odată. Alege ce te entuziasmează cel mai mult azi și dă-i cea mai bună energie.", question: "Ce merită cea mai bună energie a ta azi?" },
      { title: "Lasă-te surprins", body: "Unele din cele mai bune lucruri ale tale se întâmplă neplanificat. Lasă loc pentru spontaneitate — acolo trăiește magia ta.", question: "Când a dus spontaneitatea la ceva grozav?" },
      { title: "Puterea varietății", body: "Să faci același lucru în fiecare zi îți omoară energia. Construiește varietate în rutina ta.", question: "Ce varietate vei adăuga în ziua ta?" },
      { title: "Corpul tău conduce", body: "Răspunsul sacral îți spune ce e corect. Gâtul îți spune ce să comunici. Lasă corpul să conducă și mintea să urmeze.", question: "Spre ce te conduce corpul tău?" },
      { title: "Rapid nu înseamnă nesăbuit", body: "Să te miști rapid e natura ta. Dar viteza cu conștientizare e diferită de viteza fără conștientizare. Rămâi prezent chiar când te miști repede.", question: "Unde poți încetini suficient să rămâi prezent?" },
      { title: "Satisfacție și pace", body: "Semnătura ta e atât satisfacție cât și pace. Când ambele sunt prezente, știi că ești pe drumul bun.", question: "Simți atât satisfacție cât și pace acum?" },
      { title: "Multi-tracking", body: "Să ai trei proiecte simultan nu e o tulburare. E cum ești proiectat. Cheia e că toate trei te entuziasmează.", question: "Proiectele tale actuale încă te entuziasmează?" },
      { title: "Comunică schimbările", body: "Când pivotezi, spune oamenilor. Nu pentru a cere permisiune — pentru a menține încrederea.", question: "Cine trebuie să afle despre o schimbare pe care o faci?" },
      { title: "Odihnă între rafale", body: "Lucrezi în rafale puternice. Între acele rafale, ai nevoie de odihnă reală. Nu scrolling. Nu planificare. Odihnă.", question: "Te odihnești între rafalele tale?" },
      { title: "Ai încredere în scurtăturile tale", body: "Mintea ta găsește calea eficientă natural. Alții poate nu înțeleg de ce ai sărit de la A la D, dar tu știi că funcționează.", question: "Ce scurtătură îți arată mintea acum?" },
      { title: "Tipul corect de ocupat", body: "A fi ocupat nu e același lucru cu a fi productiv. Ai nevoie de tipul corect de ocupat — cel care te lasă satisfăcut, nu doar obosit.", question: "Ocupația ta te lasă satisfăcut sau doar obosit?" },
      { title: "Managementul energiei", body: "Energia ta e puternică dar nu nelimitată. Azi, observă ce adaugă la energia ta și ce scade din ea.", question: "Ce a adăugat energie zilei tale? Ce a scăzut?" },
      { title: "Urmează entuziasmul", body: "Entuziasmul e busola ta. Nu logica, nu obligația, nu ce așteaptă alții. Când ceva te entuziasmează, asta e corpul spunând da.", question: "Ce te entuziasmează dar ai amânat?" },
      { title: "Ritmul tău e al tău", body: "Unele zile te miști cu viteza luminii. Altele trebuie să încetinești. Ambele sunt valide.", question: "Ce ritm se simte corect pentru azi?" },
      { title: "Nu renunți, evoluezi", body: "Când renunți la ceva, nu e mereu a renunța. Uneori e a evolua. Depășești lucruri mai repede decât majoritatea — asta e normal pentru tine.", question: "Ce ai depășit?" },
      { title: "Jongleria", body: "Jonglezi bine. Dar chiar și jonglerii buni trebuie să pună unele mingi jos uneori. Ce poți pune jos azi fără vinovăție?", question: "Ce poți pune jos azi?" },
      { title: "Scânteia de dimineață", body: "Primul lucru care te entuziasmează dimineața e adesea cel mai important de acționat. Înainte ca lista de sarcini să preia controlul, urmează scânteia.", question: "Care a fost primul lucru care te-a entuziasmat azi dimineață?" },
      { title: "Contribuția ta", body: "Aduci energie și impuls la tot ce atingi. Echipele au nevoie de scânteia ta. Proiectele au nevoie de viteza ta. Asumă-ți contribuția.", question: "Unde are energia ta cel mai mare impact?" },
      { title: "Răbdare cu tine", body: "Aștepți mult de la tine pentru că știi de ce ești capabil. Dar chiar și tu ai nevoie de răbdare. Creșterea nu e mereu rapidă.", question: "Unde ai nevoie de mai multă răbdare cu tine?" },
      { title: "Diseară, verifică", body: "Înainte de somn, întreabă-te: am urmat entuziasmul azi? Am informat înainte să mă mișc? M-am odihnit între rafale?", question: "Ai urmat entuziasmul azi?" },
      { title: "Mâine aduce opțiuni", body: "Mâine va aduce lucruri noi la care să răspunzi. Nu trebuie să ai totul figurat diseară. Ai încredere că răspunsul tău va fi clar.", question: "Ce opțiune aștepți cu nerăbdare să explorezi?" },
      { title: "Dansul facerii", body: "Viața ta e un dans între a face și a fi. Azi, observă de care ai nevoie mai mult. Ambele te servesc — în momentul potrivit.", question: "Ai nevoie de mai mult a face sau mai mult a fi azi?" },
    ],
    Manifestor: [
      { title: "Tu ești începutul", body: "Tu începi lucruri. Asta e darul tău. Nu ai nevoie de permisiune — ai nevoie să informezi oamenii din jur că ești pe cale să o faci.", question: "Ce ești gata să începi?" },
      { title: "Informează, nu cere", body: "A informa nu e a cere permisiune. E a da celorlalți o șansă să se pregătească pentru ce ești pe cale să pui în mișcare.", question: "Cine ar beneficia să știe următoarea ta mișcare?" },
      { title: "Pacea e busola ta", body: "Când te simți în pace, ești pe drumul bun. Când simți furie, ceva sau cineva încearcă să te controleze.", question: "Unde încearcă furia să-ți spună ceva?" },
      { title: "Impactul e inevitabil", body: "Tot ce faci are un impact asupra oamenilor din jurul tău. Nu pentru că încerci — pentru că așa funcționează energia ta. Asumă-l.", question: "Ce impact ai avut azi pe care nu l-ai intenționat?" },
      { title: "Odihnă după inițiere", body: "Te miști în rafale puternice. După fiecare inițiere, ai nevoie de odihnă reală. Nu vinovăție pentru odihnă — odihnă reală, fără scuze.", question: "Te odihnești suficient între inițierile tale?" },
      { title: "Independența ta contează", body: "Faci cea mai bună muncă singur sau în termenii tăi. Nu e antisocial — e cum ești proiectat. Protejează-ți independența.", question: "Ce independență trebuie să protejezi azi?" },
      { title: "Nu toți vor înțelege", body: "Te miști diferit față de majoritatea. Nu toți vor înțelege ritmul tău, independența ta, nevoia de autonomie. E în regulă.", question: "A cui opinie porți cu tine și ar trebui s-o pui jos?" },
      { title: "Impulsul de a crea", body: "Când simți impulsul de a crea ceva, nu-l gândi prea mult. Informează oamenii relevanți, apoi mișcă-te.", question: "Ce impuls creativ ai ținut în tine?" },
      { title: "Furia ca informație", body: "Furia ta nu e un defect de caracter. E informație că libertatea ta e compromisă. Ascult-o, apoi acționează pe baza informației.", question: "Ce îți spune furia ta săptămâna asta?" },
      { title: "Nu ai nevoie de echipă", body: "Poți face lucruri remarcabile singur. Echipele pot ajuta, dar doar dacă nu te încetinesc sau nu încearcă să controleze procesul tău.", question: "Unde te-ar servi mai bine să lucrezi singur?" },
      { title: "Inițiază cu intenție", body: "Înainte să începi ceva, fii clar de ce. Inițierile tale au putere — direcționează-le spre ce contează cu adevărat.", question: "Inițiativa ta actuală e aliniată cu ce contează cel mai mult?" },
      { title: "Lasă controlul", body: "Inițiezi, dar nu trebuie să controlezi rezultatul. Începe lucruri, informează oamenii, apoi lasă-le să se desfășoare.", question: "Ce rezultat încerci să controlezi?" },
      { title: "Solitudinea e combustibil", body: "Timpul singur nu e singurătate pentru tine — e reîncărcare. Ai nevoie de solitudine la fel cum Generatorii au nevoie de angajament.", question: "Când ai avut ultima dată solitudine de calitate?" },
      { title: "Informează pentru a conecta", body: "A informa e cum construiești încredere. Când oamenii știu ce faci și de ce, te susțin în loc să te reziste.", question: "Cine din viața ta ar beneficia de mai multă informație de la tine?" },
      { title: "Claritate de dimineață", body: "Dimineața e adesea când impulsurile tale creative sunt cele mai puternice. Înainte ca lumea să-ți ceară atenția, verifică cu propriile impulsuri.", question: "Ce impuls a apărut dimineața asta?" },
      { title: "Limitele nu sunt ziduri", body: "Pui limite puternice. Asta nu te face rece — te face clar. Oamenii clari atrag relații clare.", question: "Ce limită trebuie să consolidezi?" },
      { title: "Ritmul tău", body: "Nu lucrezi pe un program 9-17. Lucrezi în rafale de creație intensă urmate de odihnă. Onorează acel ritm în loc să lupți cu el.", question: "Programul tău actual onorează ritmul tău natural?" },
      { title: "Curajul de a începe", body: "A începe ceva nou cere curaj. Ai acel curaj incorporat. Azi, amintește-ți că lumea are nevoie de oameni care încep lucruri.", question: "Ce ai începe dacă nu ai avea nicio frică?" },
      { title: "Diseară, revizuiește impactul", body: "Înainte de somn, reflectează asupra impactului pe care l-ai avut azi. Nu bun sau rău — doar impact. Conștientizarea e primul pas.", question: "Care a fost cel mai mare impact al tău azi?" },
      { title: "Tu setezi ritmul", body: "În orice cameră, în orice proiect, tu setezi natural ritmul. Alții urmează conducerea ta. Fii intenționat cu privire la unde conduci oamenii.", question: "Unde conduci oamenii acum?" },
      { title: "Nu ești stricat, ești proiectat", body: "Dacă oamenii ți-au spus că ești prea intens, prea independent sau prea mult — asta e disconfortul lor, nu defectul tău de proiectare.", question: "Ce parte din tine ți s-a spus să o temperezi?" },
      { title: "Creează întâi, optimizează apoi", body: "Ești construit să începi lucruri, nu să le perfecționezi. Pune-le în mișcare, apoi predă detaliile cuiva care prosperă cu ele.", question: "Ce ai perfecționat în loc să începi ceva nou?" },
      { title: "Focul tău", body: "Porți un foc interior pe care majoritatea nu-l au. Are nevoie de expresie, nu de suprimare. Găsește ce-l lasă să ardă azi.", question: "Ce cere focul tău azi?" },
      { title: "Răbdare cu lumea", body: "Lumea se mișcă mai lent decât tine. Nu e vina lumii sau a ta. Răbdarea nu e slăbiciune — e conștientizare strategică.", question: "Unde ai nevoie de răbdare cu lumea acum?" },
      { title: "Mâine începi din nou", body: "Fiecare zi e o nouă șansă de a iniția ceva. Nu porți impulsul de ieri — creezi pe al zilei de azi. Trezește-te gata să începi.", question: "Ce vei începe mâine?" },
    ],
    Projector: [
      { title: "Așteaptă invitația", body: "Oportunitățile corecte vin cu recunoaștere. Când cineva îți vede cu adevărat valoarea și te invită, asta e deschiderea ta. Înainte de asta, răbdare.", question: "Unde aștepți o invitație acum?" },
      { title: "Energia ta e focalizată", body: "Nu ai aceeași energie ca Generatorii. Puterea ta e în rafale concentrate, nu în producție susținută. Lucrează inteligent, odihnește-te des.", question: "Cum ți-ai gestionat energia azi?" },
      { title: "Recunoașterea contează", body: "Ai nevoie să fii văzut pentru cine ești, nu doar ce faci. Când vine recunoașterea, te alimentează. Când nu vine, odihnește-te și refocalizează.", question: "Cine te vede cu adevărat?" },
      { title: "Ghidează, nu face", body: "Nu ești aici să faci toată munca singur. Ești aici să vezi, să înțelegi și să ghidezi. Lasă pe alții să se ocupe de execuție.", question: "Unde faci prea mult singur?" },
      { title: "Amărăciunea e un semnal", body: "Când te simți amărât, înseamnă că lucrezi prea mult și ești prea puțin recunoscut. Nu e autocompătimire — e sistemul tău spunându-ți să recalibrezi.", question: "Unde apare amărăciunea?" },
      { title: "Calitate peste cantitate", body: "Ești construit pentru profunzime, nu volum. Un insight profund înțeles valorează mai mult decât zece observații de suprafață.", question: "Ce insight porți cu tine?" },
      { title: "Odihna nu e opțională", body: "Odihna nu e lene pentru tine — e esențială. Fără odihnă regulată, focusul tău se deteriorează și amărăciunea crește.", question: "Ai integrat odihnă în ziua ta?" },
      { title: "Percepția ta e darul tău", body: "Vezi lucruri pe care alții le ratează. Tipare în oameni, sisteme, relații. Acea percepție e valoroasă — dar doar când ești invitat.", question: "Ce ai observat ce nimeni nu a întrebat?" },
      { title: "Mediul potrivit", body: "Ești sensibil la mediul tău. Spațiul greșit te golește. Spațiul corect te energizează. Alege-ți mediile deliberat.", question: "Mediul tău actual te susține?" },
      { title: "Succesul e semnătura ta", body: "Când trăiești corect — așteptând invitații, odihnindu-te, împărtășind înțelepciunea când ești întrebat — simți succes.", question: "Unde simți succes acum?" },
      { title: "Nu toți merită ghidarea ta", body: "Înțelepciunea ta e prețioasă. Nu o oferi oamenilor care nu au cerut-o. Păstrează-ți energia pentru cei care chiar vor perspectiva ta.", question: "Cine chiar vrea ghidarea ta?" },
      { title: "Studiază ce te interesează", body: "Ești un student natural. Lucrurile pe care le studiezi devin fundația înțelepciunii pe care o împărtășești.", question: "Ce studiezi acum?" },
      { title: "Ritmul tău e diferit", body: "Lucrezi diferit față de ce așteaptă lumea. Ore mai scurte, focus mai adânc, mai multă odihnă. Nu e slăbiciune — e designul tău funcționând corect.", question: "Îți onorezi ritmul natural?" },
      { title: "Limite cu vampirii de energie", body: "Oamenii îți absorb energia focalizată. Fără limite, ajungi golit de haosul altora. Protejează-ți energia deliberat.", question: "Cine îți golește energia?" },
      { title: "Invitația va veni", body: "Dacă îți faci treaba — învățând, odihnindu-te, fiind tu — invitațiile corecte te vor găsi. Ai încredere în timing.", question: "Ce invitație speri?" },
      { title: "Verificare de odihnă de dimineață", body: "Înainte să începi ziua, verifică: sunt suficient de odihnit? Dacă nu, ajustează planul.", question: "Cât de odihnit te simți dimineața asta?" },
      { title: "Vezi sistemul", body: "Ai un dar de a vedea cum funcționează sistemele. Azi, folosește acel dar pentru tine: privește-ți propriile tipare.", question: "Ce tipar rulezi pe autopilot?" },
      { title: "Înțelepciunea cere timp", body: "Cele mai bune insight-uri ale tale vin după procesare, nu în momentul respectiv. Dă-ți timp să gândești înainte să împărtășești.", question: "Ce are nevoie de mai mult timp de procesare?" },
      { title: "Mai puțin e mai mult", body: "Pentru tine, a face mai puțin produce adesea mai mult. O oră focalizată bate patru împrăștiate.", question: "Unde poți face mai puțin și produce mai mult?" },
      { title: "Diseară, simte-ți succesul", body: "Înainte de culcare, găsește un moment din azi unde ai simțit succes. Nu productiv — de succes. E o diferență.", question: "Ce a simțit ca succes genuinim azi?" },
      { title: "Răbdarea e putere", body: "Așteptarea nu e pasivă pentru tine — e puternică. Fiecare moment în care aștepți invitația corectă, construiești energie.", question: "Pentru ce construiești energie?" },
      { title: "Nu ești stricat", body: "Dacă nu poți ține pasul cu ritmul Generatorilor, nu ești stricat. Ești proiectat diferit. Puterea ta e în precizie, nu rezistență.", question: "Unde te-ai comparat cu Generatorii?" },
      { title: "Da selectiv", body: "Fiecare da te costă energie. Fii selectiv. Da-ul corect deschide uși. Da-ul greșit le închide prin golirea ta.", question: "La ce ar fi trebuit să spui nu recent?" },
      { title: "Valoarea ta e inerentă", body: "Nu trebuie să-ți dovedești valoarea prin supramuncă. Valoarea ta e în cine ești și cum vezi lumea. Asta e suficient.", question: "Unde încerci să-ți dovedești valoarea?" },
      { title: "Siesta e o strategie", body: "O odihnă de la mijlocul zilei nu e slăbiciune — e strategică. Energia ta se reînnoiește prin odihnă, nu prin a împinge mai tare.", question: "Poți integra o odihnă scurtă azi?" },
    ],
    Reflector: [
      { title: "Mediul tău e totul", body: "Absorbi energia fiecărui spațiu în care intri. Mediul corect te face să prosperi. Cel greșit te ofilește. Alege cu grijă.", question: "Cum se simte mediul tău actual?" },
      { title: "Tu ești oglinda", body: "Reflecți sănătatea comunității din jurul tău. Când comunitatea prosperă, tu simți. Când se luptă, tu simți și asta.", question: "Ce reflectă comunitatea ta acum?" },
      { title: "Dă-i o lună", body: "Deciziile mari au nevoie de un ciclu lunar complet. Nu pentru că ești indecis — pentru că claritatea ta vine lent și temeinic.", question: "Ce decizie îi dai timp?" },
      { title: "Surpriza e busola ta", body: "Când te simți surprins și încântat, ești pe drumul bun. Când te simți dezamăgit, ceva din jurul tău are nevoie de atenție.", question: "Ce te-a surprins plăcut recent?" },
      { title: "Ești rar", body: "Doar aproximativ 1% din oameni au designul tău. Asta te face neobișnuit — și neobișnuit de valoros. Perspectiva ta contează.", question: "Ce perspectivă aduci pe care alții o ratează?" },
      { title: "Identitate fluidă e normal", body: "Te simți diferit în funcție de cine ești. Nu e instabilitate — e designul tău. Ești menit să testezi, nu să fii fix.", question: "Cu cine ai fost recent care a simțit bine?" },
      { title: "Protejează-ți sensibilitatea", body: "Sensibilitatea ta e superputerea ta, nu slăbiciunea. Dar are nevoie de protecție. Zgomotul, haosul și negativitatea te afectează mai mult.", question: "De ce te protejezi azi?" },
      { title: "Dezamăgirea spune adevărul", body: "Când te simți dezamăgit, mediul sau comunitatea nu trăiesc la potențialul lor. Asta e informație importantă — nu doar emoție.", question: "Ce te dezamăgește acum?" },
      { title: "Vorbește cu mulți oameni", body: "Când iei o decizie, vorbește cu oameni diferiți despre ea. Fiecare conversație relevă un unghi nou. După o lună, apare claritatea.", question: "Cu cine ar trebui să vorbești despre decizia ta actuală?" },
      { title: "Oamenii potriviți contează cel mai mult", body: "Mai mult decât orice alt tip, depinzi de calitatea oamenilor din jurul tău. Alege-ți cercul interior cu grijă extremă.", question: "Cine e în cercul tău interior — și ar trebui să fie?" },
      { title: "Nu toată energia e a ta", body: "Azi, observă când simți ceva ce nu e al tău. Anxietatea, entuziasmul, tristețea — poate aparțin cuiva din apropiere.", question: "Ce emoție porți care nu e a ta?" },
      { title: "Decizii lente sunt decizii puternice", body: "Deciziile tale devin mai puternice cu timpul, nu mai slabe. Deciziile rapide sunt pentru alte tipuri. Puterea ta e în răbdare.", question: "Ce decizie s-a îmbunătățit prin așteptare?" },
      { title: "Luna și tu", body: "Energia ta se schimbă cu ciclul lunar. Unele săptămâni te simți clar și puternic. Altele, cețos și nesigur. Ambele sunt normale.", question: "Unde ești în ciclul tău de energie acum?" },
      { title: "Spațiu să fii tu", body: "Ai nevoie de timp regulat singur — nu ca să fii singur, ci să descoperi ce e al tău versus ce ai absorbit de la alții.", question: "Când ai petrecut ultima dată timp de calitate singur?" },
      { title: "Tu vezi adevărul", body: "Pentru că reflecți ce e în jurul tău, vezi adesea adevărul unei situații înainte de oricine altcineva. Ai încredere în ce vezi.", question: "Ce adevăr vezi pe care alții nu-l văd?" },
      { title: "Audit de mediu", body: "Azi, fii atent la cum te fac diferite spații să te simți. Biroul, cafeneaua, casa ta. Corpul îți spune unde aparții.", question: "Unde te-ai simțit cel mai bine azi?" },
      { title: "Schimbarea nu e trădare", body: "Te schimbi în funcție de cine ești și unde ești. Nu e a fi fals — e a fi receptiv. Onorează-ți fluiditatea.", question: "Cum te-ai schimbat azi în funcție de mediu?" },
      { title: "Verificare sănătate comunitate", body: "Ești canarul din mina de cărbune pentru comunitatea ta. Dacă te simți greșit, ceva în colectiv ar putea fi greșit.", question: "Care e sănătatea comunității tale acum?" },
      { title: "Așteaptă cu intenție", body: "Așteptarea nu e pasivă pentru tine. E adunare activă — de informații, perspective, sentimente. Procesezi mai mult decât realizezi.", question: "Ce procesezi activ acum?" },
      { title: "Diseară, eliberează ce nu e al tău", body: "Înainte de somn, eliberează conștient energiile pe care le-ai absorbit azi. Nu tot ce ai simțit a fost al tău. Lasă-le și revino la tine.", question: "Ce poți elibera înainte de somn?" },
      { title: "Raritatea ta e forța ta", body: "A fi atât de diferit de toți ceilalți poate simți singur. Dar raritatea ta îți dă o perspectivă pe care nimeni altcineva nu o are.", question: "Ce dar îți dă unicitatea ta?" },
      { title: "Răbdare cu claritatea ta", body: "Claritatea va veni. Vine mereu. Dar vine pe propriul ei program, nu când o ceri. Fii răbdător cu procesul tău.", question: "Ce aștepți să devină clar?" },
      { title: "Viața de testare", body: "Ești proiectat să guști experiențe diferite, nu să te angajezi la o singură aromă pentru totdeauna. Dă-ți permisiunea de a explora.", question: "Ce experiență nouă te curiozită?" },
      { title: "Prezența ta contează", body: "Uneori cel mai important lucru pe care îl faci e pur și simplu să fii prezent. Prezența ta schimbă energia unei camere — în bine.", question: "Unde contează prezența ta cel mai mult?" },
      { title: "Verificare de mediu de dimineață", body: "Cum se simte primul spațiu în care intri dimineața? Dacă nu se simte bine, ajustează-l. Mediul tău de dimineață setează toată ziua.", question: "Cum se simte mediul tău de dimineață?" },
    ],
  },

  // For remaining languages, we use the EN structure as base
  // These will be populated in a future iteration with Alex's validation
  // For now, they fall back to EN
}

// Fallback chain: requested lang → en
function getThoughtsForType(hdType, language) {
  const lang = DAILY_THOUGHTS[language] || DAILY_THOUGHTS['en']
  return lang[hdType] || lang['Generator']
}

// Get today's thought — date-seeded, no repeat within same month
export function getDailyThought(hdType, language = 'en') {
  const thoughts = getThoughtsForType(hdType, language)

  const today = new Date()
  const dayOfMonth = today.getDate() - 1  // 0-indexed
  const monthSeed = today.getMonth() + today.getFullYear() * 12

  // Shuffle based on month so order changes monthly
  const shuffled = [...thoughts]
  let seed = monthSeed
  for (let i = shuffled.length - 1; i > 0; i--) {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff
    const j = seed % (i + 1)
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }

  const index = dayOfMonth % shuffled.length
  return shuffled[index]
}

export default DAILY_THOUGHTS