// Daily Thoughts Bank
// 30 thoughts per HD type × 10 languages
// Zero API cost — all static content
// getDailyThought(hdType, lang) returns { title, body, question } rotating daily

const THOUGHTS = {
  en: {
    Generator: [
      { title: "The Power of Response", body: "Your greatest strength isn't in what you start — it's in what you respond to. Today, notice what genuinely pulls your energy forward versus what you're pushing yourself toward. Your sacral knows the difference, even when your mind tries to override it.", question: "What is pulling you forward right now that you haven't said yes to yet?" },
      { title: "Satisfaction as Compass", body: "Satisfaction isn't a luxury — it's your navigation system. When you feel deeply satisfied at the end of the day, you know you were aligned. When frustration dominates, something needs to shift. Not tomorrow. Today.", question: "Where in your life are you choosing obligation over satisfaction?" },
      { title: "Your Energy Speaks", body: "Your body is constantly communicating. That gut feeling, that burst of excitement, that heavy reluctance — these aren't random. They're your most reliable guidance system, more accurate than any plan your mind could make.", question: "What did your body try to tell you today that you almost ignored?" },
      { title: "Wait Before You Leap", body: "Waiting to respond doesn't mean being passive. It means being selective. The most powerful Generators aren't the ones who say yes to everything — they're the ones who wait until their whole body lights up before committing.", question: "What are you saying yes to out of guilt rather than genuine excitement?" },
      { title: "Frustration Is a Teacher", body: "When frustration visits, don't push it away. It's telling you something important: you're either doing the wrong work, or doing the right work the wrong way. Both are fixable — but only if you listen first.", question: "What frustration keeps returning, and what might it be trying to show you?" },
      { title: "Rest as Strategy", body: "You have sustainable energy, but sustainable doesn't mean infinite. The Generator who rests well responds better. Sleep isn't lost productivity — it's preparation for tomorrow's clarity.", question: "Are you resting enough to show up fully tomorrow?" },
      { title: "The Right Work", body: "There's a difference between being busy and being aligned. You can fill every hour and still feel empty. Or you can do three things that light you up and feel completely alive. Quality of engagement matters more than quantity.", question: "If you could only do three things tomorrow, what would they be?" },
      { title: "Trust the Gut", body: "Your sacral response is faster than thought. That immediate 'uh-huh' or 'uh-uh' arrives before your mind has time to analyze. The challenge isn't hearing it — it's trusting it when it contradicts your plans.", question: "When was the last time you trusted your gut and it turned out right?" },
      { title: "Energy Management", body: "Not everything that asks for your energy deserves it. You're designed to have energy for what's correct for you — but that means saying no to what isn't. Every false yes costs you a true one.", question: "What is currently draining energy that doesn't belong in your life?" },
      { title: "Building Through Response", body: "The most meaningful things in your life probably weren't planned — they were responded to. A conversation, an opportunity, a feeling that said 'this matters.' Trust that the right things will continue to show up.", question: "What showed up recently that you haven't fully responded to yet?" },
      { title: "Mastery Takes Time", body: "Generators build mastery through sustained engagement with what satisfies them. You're not meant to dabble — you're meant to go deep. But only into what genuinely excites your energy.", question: "What skill or craft deserves more of your devoted attention?" },
      { title: "The Sacral Check-In", body: "Before your next commitment, pause. Does your body expand or contract? Do you feel pulled forward or pushed? This simple check can save you months of frustration.", question: "What upcoming commitment needs a genuine gut check?" },
      { title: "Celebrate Small Wins", body: "Satisfaction builds on itself. Each moment of genuine fulfillment strengthens your ability to find the next one. Don't wait for the big breakthrough — celebrate the daily alignment.", question: "What small thing today brought you unexpected satisfaction?" },
      { title: "False Yes, True Cost", body: "Every time you say yes when your gut says no, you pay twice: once in energy spent on the wrong thing, once in the opportunity you missed because you were unavailable.", question: "Where are you over-committed because you couldn't say no?" },
      { title: "Your Pace Is Perfect", body: "You're not behind. The Generator's path isn't linear — it's responsive. You build momentum through aligned action, and that can look different every day. Trust your rhythm.", question: "Are you judging your pace by someone else's timeline?" },
      { title: "What Lights You Up", body: "Pay attention to what makes time disappear. Those flow states aren't accidents — they're your design showing you where you belong. Follow the energy, not the logic.", question: "When did you last lose track of time doing something you love?" },
      { title: "Evening Reflection", body: "The quality of your day isn't measured by tasks completed but by satisfaction felt. A day full of aligned work leaves you tired but fulfilled. A day of misaligned hustle leaves you exhausted and empty.", question: "Does tonight's tiredness feel like fulfillment or depletion?" },
      { title: "Responding to Life", body: "You don't have to figure everything out. Your job is to show up, stay open, and respond to what resonates. Life is constantly offering you options — your body is constantly telling you which ones are yours.", question: "What has life been offering that you've been too busy to notice?" },
      { title: "The Power of No", body: "A clear no is an act of self-respect. It protects your energy for what truly matters. People may not always understand your no, but your body will always thank you for it.", question: "What do you need to say no to this week?" },
      { title: "Sustainable Fire", body: "Your sacral energy is like a sustainable fire — it burns consistently when fueled by the right things. But throw in obligations that don't belong, and it smokes instead of flames.", question: "What's creating smoke in your life instead of clean fire?" },
      { title: "Morning Intention", body: "Before the day starts, check in. Not with your to-do list, but with your body. What does it want to move toward? What does it want to rest from? Let that guide your first decision.", question: "What does your body want to move toward today?" },
      { title: "Connection Through Work", body: "Generators often connect most deeply with others through shared work. Doing something alongside someone creates bonds that conversation alone cannot. Your energy is magnetic when engaged.", question: "Who do you want to build something with?" },
      { title: "The Waiting Game", body: "Waiting to respond can feel passive in a world that rewards initiative. But your waiting isn't passive — it's discriminating. You're not doing nothing; you're preparing to do the right thing.", question: "What are you waiting for that you're trying to force instead?" },
      { title: "Body Over Mind", body: "Your mind will always have opinions about what you should do. Your body knows what you need to do. When they conflict, the body is almost always right for Generators.", question: "Where are you overriding your body's wisdom with mental logic?" },
      { title: "Creative Frustration", body: "Sometimes frustration means you're working on the wrong thing. Other times it means you're about to break through on the right thing. The difference? Your body still wants to engage with breakthroughs.", question: "Is your current frustration a signal to stop or to push through?" },
      { title: "Energy Boundaries", body: "Your energy is generous but not unlimited. The people and projects that receive it should earn it through genuine resonance, not guilt or obligation.", question: "Who or what is receiving energy they haven't earned?" },
      { title: "The Full Battery", body: "A Generator with a full battery is unstoppable — magnetic, productive, alive. A depleted Generator is frustrated, foggy, and resentful. Battery management isn't selfish; it's essential.", question: "How charged is your battery right now, honestly?" },
      { title: "Work as Play", body: "When your work feels like play, you're aligned. Not every moment will be joyful, but the overall trajectory should feel like something you'd choose even if no one was watching.", question: "Would you still do what you do if no one could see the results?" },
      { title: "Trust the Process", body: "You can't respond to what hasn't shown up yet. Patience isn't your weakness — it's your strategy. The right things come when you stop chasing and start being available.", question: "What would change if you trusted that the right opportunity will find you?" },
      { title: "Nightly Gratitude", body: "Before sleep, find one moment from today where you felt genuinely satisfied. Not productive — satisfied. That feeling is your compass needle pointing north. Follow it tomorrow.", question: "What was your most satisfying moment today?" }
    ],
    'Manifesting Generator': [
      { title: "Multi-Passionate by Design", body: "You're not scattered — you're designed to explore multiple paths. The world may tell you to pick one thing, but your energy thrives on variety. The key is following genuine excitement, not obligation.", question: "Which of your many interests is calling loudest right now?" },
      { title: "The Art of the Pivot", body: "Changing direction isn't failure — it's refinement. When you pivot because something stopped feeling right, you're honoring your design. Just remember: inform the people who'll be affected.", question: "What needs to change direction, and who needs to know?" },
      { title: "Speed as Superpower", body: "You process faster than most people around you. That's not impatience — it's efficiency. But learn to distinguish between skipping unnecessary steps and cutting corners that matter.", question: "Where is your speed serving you, and where is it costing you?" },
      { title: "Inform, Don't Ask", body: "Your strategy includes informing — not asking permission. There's a difference between 'I'm going to do this' and 'Can I do this?' The first honors your nature. Just make sure people know what's coming.", question: "Who do you need to inform about a change you're already making?" },
      { title: "The Satisfaction Check", body: "Like the Generator, satisfaction is your sign of alignment. But for you, it might come in bursts rather than sustained waves. Multiple small satisfactions in a day means you're on track.", question: "How many moments of genuine satisfaction did you have today?" },
      { title: "Frustration with Patience", body: "Your biggest frustration often comes from having to slow down for others. The world doesn't move at your speed. Finding peace with that — without dimming your fire — is your ongoing practice.", question: "Where can you be patient without losing your momentum?" },
      { title: "Non-Linear Genius", body: "Your path to mastery isn't step-by-step — it's leap by leap. You skip steps intuitively, seeing connections others miss. Trust this, but verify: did you skip steps wisely or impatiently?", question: "What did you skip recently that might need revisiting?" },
      { title: "Energy in Motion", body: "Your energy needs movement. Physical, mental, creative — stagnation is your enemy. When you feel stuck, the answer is rarely to think harder. It's to move differently.", question: "What kind of movement would unstick you right now?" },
      { title: "Permission to Quit", body: "Not everything you start needs to be finished. If your energy leaves, the project isn't yours anymore. Quitting the wrong thing creates space for the right thing.", question: "What have you been dragging along that you should have dropped?" },
      { title: "The Connection Maker", body: "Your superpower is seeing connections between seemingly unrelated fields. That weird combination of interests isn't random — it's where your unique value lives.", question: "What two seemingly unrelated interests could you combine?" },
      { title: "Response Before Action", body: "Even with your speed, the best outcomes come when you respond to something rather than initiate from scratch. Wait for the pull, then move fast.", question: "Are you responding or forcing right now?" },
      { title: "Sustainable Intensity", body: "You can go incredibly fast — for a while. Then you need a full stop. Honor the cycles of intensity and rest. Both are productive for your design.", question: "Are you in a time for intensity or a time for rest?" },
      { title: "Multiple Mastery", body: "You might not master one thing in the traditional sense, but you can master the intersections. Your unique blend of skills and interests creates something no specialist can replicate.", question: "What unique combination of skills do you bring that nobody else does?" },
      { title: "The Guilt of Variety", body: "Society rewards specialization. You're designed for synthesis. Let go of the guilt about having too many interests — that breadth is exactly what makes you valuable.", question: "What interest have you been suppressing because it seems impractical?" },
      { title: "Fast Doesn't Mean Careless", body: "You can move quickly AND with care. Speed and attention to detail aren't opposites — they just require you to know which details actually matter.", question: "What details matter most in what you're building right now?" },
      { title: "The Informing Practice", body: "Before you pivot, take 30 seconds to inform the people affected. It prevents 90% of the friction in your life and relationships. Quick text, brief conversation — that's all it takes.", question: "Who deserved a heads-up that you forgot to give recently?" },
      { title: "Excitement as GPS", body: "Follow what excites you, not what makes logical sense. Your excitement is your body's way of saying 'this is correct for you.' Logic is useful, but it can't feel into alignment the way your gut can.", question: "What excites you right now that doesn't make logical sense?" },
      { title: "The Power of Both", body: "You don't have to choose between your passions. The question isn't 'which one?' — it's 'how do I make room for both?' Sometimes the answer is sequencing. Sometimes it's simultaneously.", question: "How can you make room for two things you love this week?" },
      { title: "Healthy Shortcuts", body: "Your ability to skip steps is a gift when used wisely. Before skipping, ask: will this save time without sacrificing quality? If yes, skip confidently. If no, slow down this once.", question: "What shortcut saved you time today without cutting quality?" },
      { title: "People and Pace", body: "Not everyone can keep up with you, and that's fine. The right people for your life will appreciate your speed. The wrong ones will constantly ask you to slow down.", question: "Who in your life appreciates your pace, and who tries to slow you down?" },
      { title: "Evening Reset", body: "Your busy day needs a clean ending. Before bed, mentally close each project and interest. Tomorrow, you'll pick up what still has energy. Let go of what doesn't.", question: "What from today can you close and release tonight?" },
      { title: "The Gift of Dissatisfaction", body: "When you feel dissatisfied despite being busy, it's not laziness or ingratitude. It's your design telling you the current mix isn't right. Adjust the ingredients, not the chef.", question: "What needs adjusting in your current mix of activities?" },
      { title: "Creative Cross-Pollination", body: "Something you learned in one domain will solve a problem in another. Your varied interests create a mental toolkit that specialists can't match. Trust those unexpected connections.", question: "What unexpected skill helped you in a completely different area recently?" },
      { title: "Embracing the Zigzag", body: "Your path will look like a zigzag from the outside. From the inside, it's perfectly logical — each turn following energy, each pivot guided by instinct. Trust the zigzag.", question: "What recent zigzag in your path turned out to be exactly right?" },
      { title: "Your Unique Tempo", body: "You have bursts of extraordinary speed followed by necessary pauses. This isn't inconsistency — it's your natural rhythm. Work with it instead of fighting it.", question: "Are you fighting your natural rhythm or flowing with it right now?" },
      { title: "The Communication Edge", body: "When you inform people about your changes proactively, you turn potential conflict into collaboration. People can handle change — they can't handle surprise.", question: "What change are you planning that others should know about sooner rather than later?" },
      { title: "Variety Is Depth", body: "Depth doesn't always mean going deeper into one hole. Sometimes it means connecting multiple shallow wells into an underground river. Your breadth IS a form of depth.", question: "How is your variety creating something deeper than any single focus could?" },
      { title: "Morning Energy Scan", body: "Check in with your body each morning: what feels electric? What feels heavy? Follow the electricity. Table the heaviness. Your morning energy scan sets the trajectory for the whole day.", question: "What feels electric to you this morning?" },
      { title: "Impactful Presence", body: "When you're lit up by what you're doing, your energy fills the room. People notice. Opportunities arise. This isn't ego — it's your aura doing what it's designed to do.", question: "When was the last time your enthusiasm opened a door for you?" },
      { title: "Closing Loops", body: "You start many things. Some are meant to be finished; others served their purpose and can be released. The wisdom is knowing which is which. Not every thread needs to be woven to the end.", question: "What loop can you close today, either by completing or releasing it?" }
    ],
    Manifestor: [
      { title: "Initiate from Peace", body: "Your most powerful creations come from a place of inner peace, not frustration or anger. When you feel the urge to start something, check: are you moving toward something, or away from something?", question: "Is your current drive coming from peace or from anger?" },
      { title: "The Informing Practice", body: "Informing isn't asking permission — it's giving others the courtesy of knowing what's coming. It reduces resistance and smooths your path. Not because you need approval, but because it works better.", question: "Who needs to know about what you're about to set in motion?" },
      { title: "Creative Solitude", body: "You need time alone. Not because something is wrong, but because your creative power recharges in solitude. Protect this time fiercely — it's where your best ideas are born.", question: "When was the last time you had real solitude to think and create?" },
      { title: "Impact Awareness", body: "You're designed to have a big impact. That's a gift and a responsibility. The question isn't whether you'll affect others — you will. The question is whether you'll be conscious about how.", question: "What impact are you having that you might not be aware of?" },
      { title: "Anger as Signal", body: "Your anger isn't a flaw — it's information. It tells you something isn't working, something needs to change, or a boundary has been crossed. Listen to it, then choose how to act on it.", question: "What is your anger trying to tell you right now?" },
      { title: "Rest Without Guilt", body: "Your energy comes in waves. Between powerful bursts of initiation, you need real rest. This isn't laziness — it's recharging for the next creative surge. Guilt about resting only slows the recharge.", question: "Can you rest today without feeling guilty about it?" },
      { title: "Vision First", body: "You see what others can't yet see. Your visions are ahead of their time, and that can feel lonely. But the world needs people who go first. Trust what you see, even when no one else can yet.", question: "What vision are you holding that you haven't shared yet?" },
      { title: "The Power to Begin", body: "You don't need permission, invitation, or consensus. You need clarity. When you're clear about what wants to be created through you, the doing becomes effortless.", question: "What have you been waiting for permission to start?" },
      { title: "Friction Is Normal", body: "You'll encounter resistance. Not because you're doing something wrong, but because initiators naturally create disruption. The key is distinguishing between productive friction and unnecessary conflict.", question: "What resistance are you meeting — is it productive or avoidable?" },
      { title: "Leading Without Controlling", body: "Your nature is to initiate, not to manage every step. Start things, set them in motion, then trust others to carry them forward. You're a spark, not a sustained flame.", question: "What have you started that you should now hand off?" },
      { title: "Selective Initiation", body: "You can start anything, but not everything. Your creative energy is powerful but not unlimited. Choose your initiations wisely — the ones that truly matter, not just the ones that come easily.", question: "What deserves your initiating energy most right now?" },
      { title: "Boundaries as Love", body: "Setting boundaries isn't selfish — it's how you maintain the energy to do what you're here to do. People who matter will understand. Those who don't weren't your people anyway.", question: "What boundary do you need to set or reinforce?" },
      { title: "The Lone Wolf Myth", body: "Independence doesn't mean isolation. You need solitude to create, but you also need people to share your creations with. Finding the balance between alone time and connection is your ongoing practice.", question: "Are you leaning too far into solitude or too far into connection right now?" },
      { title: "Timing Your Moves", body: "Not every urge to initiate needs to be acted on immediately. Sometimes the vision comes before the timing is right. Hold the vision. The moment to move will announce itself.", question: "What are you trying to launch before its time?" },
      { title: "Peaceful Power", body: "When you're in a state of peace, your decisions are cleaner, your impact is greater, and your path has less friction. Peace isn't the absence of action — it's the foundation for right action.", question: "How can you find more peace before your next big move?" },
      { title: "The Catalyst Role", body: "You start things that others finish. You open doors that others walk through. This is your role — not to do everything, but to set things in motion. Own that role without trying to also be the sustainer.", question: "What have you catalyzed recently that's now growing without you?" },
      { title: "Creative Urges", body: "When a creative urge strikes, pay attention. Not every urge needs action, but each one carries information. What is trying to come through you? What wants to be created?", question: "What creative urge have you been ignoring?" },
      { title: "Morning Check-In", body: "Before you initiate anything today, ask: does this come from my vision or from my reaction? Vision-driven initiation creates. Reaction-driven initiation destroys. The difference changes everything.", question: "What will you initiate today, and where does the urge come from?" },
      { title: "Impact Ripples", body: "Everything you start creates ripples you may never see. Someone was changed by what you created. A door opened somewhere because you went first. Trust that your impact extends far beyond what you can measure.", question: "What ripple from your past actions might still be moving?" },
      { title: "The Right Container", body: "Your creative energy needs the right container. Too many constraints and you feel caged. Too few and your energy dissipates. Find the structure that channels your power without restricting it.", question: "Does your current structure support or restrict your creative energy?" },
      { title: "Evening Peace", body: "At the end of the day, find peace regardless of what was accomplished. Your value isn't measured by output. Some days are for creation. Others are for restoration. Both matter equally.", question: "Can you find peace with however today went?" },
      { title: "Unconventional Path", body: "Your path won't look like anyone else's. You're not following a trail — you're blazing one. Comparison is meaningless when your purpose is to go where no one has gone.", question: "Where are you trying to follow someone else's path instead of creating your own?" },
      { title: "The Waiting Manifestor", body: "Even Manifestors must sometimes wait. Not for permission, but for clarity. When the urge to act isn't clear, sitting still is wisdom, not weakness.", question: "Is now a time for action or for waiting for clarity?" },
      { title: "Anger to Fuel", body: "Anger can destroy or it can fuel. When you feel it rising, choose: will this energy tear down or build up? Channeled anger is one of the most creative forces available to you.", question: "How can you channel today's frustration into something creative?" },
      { title: "Your Aura Speaks", body: "Your energy field is strong and closed. People feel your presence before you say a word. This is your power — and it means you're always communicating, whether you intend to or not.", question: "What is your presence communicating without words?" },
      { title: "Starting Over", body: "Starting over isn't failure — it's one of your greatest abilities. Each new beginning carries the wisdom of what came before. Don't fear the restart; you're designed for it.", question: "What might benefit from a complete fresh start?" },
      { title: "Legacy Thinking", body: "What you initiate today could outlast you. Think about what you want to set in motion — not just for now, but for the long arc of impact. What matters enough to go first for?", question: "What do you want to have started that matters beyond today?" },
      { title: "The Invitation Exception", body: "Though you don't need invitations, sometimes the best opportunities arrive as one. Stay open to responding when something resonates deeply, even if you're used to going first.", question: "When was the last time you accepted an invitation that surprised you?" },
      { title: "Power and Grace", body: "You can be powerful without being forceful. True strength often looks like restraint — knowing you could act but choosing to wait for the right moment. That's mastery.", question: "Where can you show strength through restraint today?" },
      { title: "Nightly Release", body: "Release today. Whatever happened — the wins, the friction, the unfinished — let it go. Tomorrow brings new creative energy. You don't need to carry today's weight into tomorrow's creation.", question: "What from today can you fully release before sleep?" }
    ],
    Projector: [
      { title: "Wait for the Invitation", body: "Your wisdom is powerful, but only when it's received. Unsolicited advice, no matter how brilliant, often falls flat. Wait until someone asks — then watch your guidance transform them.", question: "Where are you offering wisdom that hasn't been asked for?" },
      { title: "Recognition Is Your Fuel", body: "Being seen and recognized for what you truly know isn't ego — it's essential. You thrive when people acknowledge your gifts. Seek environments where your insight is valued, not ignored.", question: "Do your current environments recognize and value your gifts?" },
      { title: "Energy Management", body: "You don't have the sustained physical energy of Generators. That's not a weakness — it's information. Work in focused bursts, rest deeply, and stop comparing your output to energy types.", question: "Are you resting enough, or trying to match someone else's pace?" },
      { title: "The Bitter Signal", body: "Bitterness is your warning light. When it appears, something is off: you're not being recognized, you're over-giving, or you're in the wrong environment. Don't judge the feeling — decode it.", question: "What is your bitterness trying to tell you?" },
      { title: "Guide, Don't Do", body: "Your genius is in seeing how to optimize systems and people. But seeing how it should be done is different from doing it yourself. Guide others to the answer — you don't have to carry it out.", question: "What are you doing yourself that you should be guiding someone else through?" },
      { title: "Mastery Matters", body: "Your authority comes through deep knowledge. Study what fascinates you relentlessly. The deeper your mastery, the more natural and magnetic your invitations become.", question: "What subject or skill deserves your deeper study right now?" },
      { title: "One-on-One Power", body: "Your greatest impact often happens in one-on-one connections. Groups dilute your energy. But one person, really seen and guided by you? That's where transformation happens.", question: "Who could benefit most from your focused, one-on-one attention?" },
      { title: "Rest Is Productive", body: "For you, rest isn't the opposite of work — it's preparation for it. Your clarity and insight sharpen with rest. A well-rested Projector sees what a tired one misses entirely.", question: "What would change if you treated rest as your most important daily task?" },
      { title: "The Right Invitation", body: "Not every invitation is the right one. Learn to feel the difference between invitations that honor your gifts and ones that just want your energy. Say yes to recognition, not exploitation.", question: "How do you distinguish between invitations that honor you and ones that use you?" },
      { title: "Bitterness to Wisdom", body: "Every experience of bitterness carries a lesson. What did you give that wasn't asked for? Where did you work without recognition? These aren't failures — they're refinements of your strategy.", question: "What lesson is hiding inside your most recent bitterness?" },
      { title: "Your Seeing Gift", body: "You see people deeply — their potential, their patterns, their blocks. This is a gift, but it must be offered at the right time. Seeing someone clearly is intimate; share it only when invited.", question: "What do you see in someone that you're waiting for the right moment to share?" },
      { title: "Energy Naps", body: "Short rest throughout the day isn't lazy — it's strategic. Even 20 minutes of genuine rest can restore your clarity completely. Build rest into your schedule, not around it.", question: "Where can you build a short rest into today?" },
      { title: "The Waiting Room", body: "Waiting for invitation can feel excruciating in an action-oriented world. But your waiting is active — you're studying, mastering, preparing. When the invitation arrives, you'll be ready.", question: "What are you mastering while you wait?" },
      { title: "Saying No to Wrong Invitations", body: "A wrong invitation accepted is worse than no invitation at all. It drains your energy, wastes your gifts, and delays the right opportunity. Your no protects your yes.", question: "What invitation should you decline to protect your energy for the right one?" },
      { title: "Systems Thinking", body: "You naturally see how systems work — and how they could work better. This perspective is rare and valuable. Don't dismiss it as obvious; most people can't see what you see.", question: "What system around you could you help optimize, if invited?" },
      { title: "Evening Reflection", body: "Before bed, ask: was I recognized today? Not by everyone — by someone. Even one moment of genuine recognition feeds your soul for days. Notice these moments and let them nourish you.", question: "Who recognized your value today, even in a small way?" },
      { title: "The Study Path", body: "Every hour you spend studying your passion is an investment in your future invitations. The deeper your knowledge, the more natural your authority, the more effortlessly invitations flow.", question: "What would you study if you gave yourself full permission?" },
      { title: "Projector Boundaries", body: "You're highly attuned to others' energy. Without boundaries, you absorb everything. Learn to notice when you're feeling someone else's emotions versus your own.", question: "What feelings are you carrying right now that might not be yours?" },
      { title: "Quality Over Quantity", body: "Your impact isn't measured in hours worked. It's measured in the depth of insight you provide in the moments that matter. One transformative conversation can be worth more than a week of grinding.", question: "What was your highest-quality contribution recently?" },
      { title: "The Projector's Aura", body: "Your aura is focused and penetrating. You see into people's core. This is why one-on-one connection is so powerful for you — and why some people feel exposed around you.", question: "How do you create safety for others when you see them so clearly?" },
      { title: "Waiting Isn't Passive", body: "Waiting for invitation is an active state. You're preparing, studying, refining. You're becoming more of who you are so that when the invitation comes, you're irresistibly ready.", question: "How are you actively preparing while you wait?" },
      { title: "The Bitter Trap", body: "Chronic bitterness means you've been operating outside your design for too long. It's a pattern, not a personality trait. You can shift it by returning to your strategy: wait, be recognized, be invited.", question: "What pattern of bitterness keeps repeating in your life?" },
      { title: "Selective Availability", body: "You don't need to be available to everyone. In fact, selective availability increases your value. The people who truly need your guidance will find a way to reach you.", question: "Are you making yourself too available to the wrong people?" },
      { title: "Morning Energy Assessment", body: "Each morning, honestly assess your energy level. On high-energy days, say yes to invitations. On low-energy days, study and rest. Your honesty about your energy prevents burnout.", question: "What does your energy level honestly tell you about today?" },
      { title: "The Teacher Within", body: "Whether or not you see yourself as a teacher, you are one. Every time you share what you've mastered, you teach. Make peace with this role — it's built into your design.", question: "What have you learned that you're uniquely positioned to teach?" },
      { title: "Recognition Hunger", body: "It's okay to want recognition. It's not ego — it's need. Like hunger for food, hunger for recognition tells you something essential is missing. Don't shame the hunger; feed it correctly.", question: "Where can you put yourself in environments where recognition flows naturally?" },
      { title: "The Observer Advantage", body: "While others are busy doing, you're busy seeing. This gives you perspectives that doers miss entirely. Your observations, shared at the right time, can redirect entire projects.", question: "What have you observed recently that could redirect something important?" },
      { title: "Projector Partnerships", body: "The right partner — in work or life — recognizes your genius and creates space for it. The wrong one drains you or ignores your gifts. Choose partnerships based on recognition, not need.", question: "Do your current partnerships recognize your gifts?" },
      { title: "Self-Recognition", body: "While external recognition feeds you, self-recognition sustains you. Know your own value independent of whether others see it. You are wise, perceptive, and valuable — with or without an audience.", question: "What do you recognize about yourself that you've been waiting for others to see?" },
      { title: "Nightly Restoration", body: "Get into bed before you're exhausted. Your body needs time to discharge energy that isn't yours. Lie down, relax, and let the day's accumulated energy release before sleep takes you.", question: "Can you get to bed 30 minutes earlier tonight?" }
    ],
    Reflector: [
      { title: "Mirror of Truth", body: "You reflect the health of your environment back to itself. When you feel good, your surroundings are probably healthy. When you don't, something around you needs attention. Trust what you feel.", question: "What is your current feeling telling you about your environment?" },
      { title: "The Lunar Cycle", body: "Big decisions deserve a full lunar cycle — about 28 days. This isn't indecisiveness; it's wisdom. You process differently through each phase of the moon, gaining perspectives others miss.", question: "What decision are you rushing that deserves a full cycle?" },
      { title: "Choose Your Environment", body: "Your environment shapes you more than most people realize. The right place lifts you. The wrong one drains you. You're not being difficult when you're particular about where you spend time.", question: "Which of your environments is lifting you and which is draining you?" },
      { title: "The Surprise Gift", body: "Your life is designed for surprise and delight. When you try to control outcomes too tightly, you block the unexpected magic that your design is built for. Leave room for wonder.", question: "When were you last genuinely surprised by something wonderful?" },
      { title: "Sampling, Not Settling", body: "You're designed to sample different experiences, not to settle into one way of being. If today feels different from yesterday, that's not inconsistency — that's your nature working perfectly.", question: "What new experience could you sample this week?" },
      { title: "Energy Protection", body: "You're an open system — you absorb and amplify everything around you. This is your superpower and your vulnerability. Choose wisely who and what you let into your energy field.", question: "What are you absorbing right now that isn't yours to carry?" },
      { title: "The Community Mirror", body: "You show communities their truth. When you're thriving in a group, the group is healthy. When you're suffering, something is wrong that everyone else might be ignoring. Your experience matters.", question: "What is your experience telling your community that they need to hear?" },
      { title: "Patience with Self", body: "You change like the moon — daily. The person you were yesterday may not be who you are today. Have patience with your own shifting nature. It's not instability; it's sensitivity.", question: "How are you different today than yesterday, and can you accept both?" },
      { title: "Reflection Not Absorption", body: "There's a difference between reflecting energy and absorbing it. Reflecting means you notice it and let it pass through. Absorbing means it gets stuck. Practice noticing without holding.", question: "What energy have you been absorbing that you need to release?" },
      { title: "The Right People", body: "Not everyone deserves access to your openness. Surround yourself with people who are healthy, kind, and authentic. You amplify whatever you're near — make sure it's worth amplifying.", question: "Who in your life consistently makes you feel better just by being near them?" },
      { title: "Moon Wisdom", body: "Track how you feel through the lunar cycle. You'll start to notice patterns — certain gates activated, certain energies available. This self-knowledge is your greatest tool for decision-making.", question: "What patterns have you noticed in yourself across different moon phases?" },
      { title: "Solitude Medicine", body: "Time alone is medicine for you. In solitude, you can finally feel what's yours versus what you've absorbed from others. Schedule it regularly, not as a luxury but as a necessity.", question: "When was your last period of genuine solitude, and how did it feel?" },
      { title: "Environmental Sensitivity", body: "The lighting, sound, energy, and people in a space all affect you deeply. You're not being high-maintenance — you're being accurate. Your sensitivity is precision, not weakness.", question: "What small environmental change would significantly improve your daily experience?" },
      { title: "The Rare Being", body: "Reflectors are about 1% of the population. Your perspective is genuinely unique. The way you see the world — holistically, reflectively, through the lens of environment — is needed and valuable.", question: "What unique perspective do you bring that others around you lack?" },
      { title: "Decisions and Time", body: "Quick decisions often feel wrong for you — because they are. Give yourself permission to say 'I need time' without apology. The people who matter will respect your process.", question: "What decision are you being pressured to make too quickly?" },
      { title: "Morning Curiosity", body: "Each morning, approach the day with curiosity rather than a plan. Who will you meet? What will surprise you? What will your environment reveal? Today is different from yesterday — let it be.", question: "What are you curious about today?" },
      { title: "The Teflon Practice", body: "Practice being a mirror, not a sponge. Let others' emotions and energies reflect off you rather than soak in. You can acknowledge what you feel without taking ownership of it.", question: "How can you reflect instead of absorb today?" },
      { title: "Community Choice", body: "The communities you belong to matter enormously. A dysfunctional community will make you feel dysfunctional. A thriving one will help you thrive. Choose your tribes carefully.", question: "Which community is most supporting your well-being right now?" },
      { title: "Embracing Change", body: "You're designed to change — daily, weekly, monthly. What excited you last week might bore you today. This isn't fickleness; it's openness. Let yourself evolve without judgment.", question: "What has changed in you recently that you're judging instead of accepting?" },
      { title: "The Full Spectrum", body: "You can experience the full spectrum of human experience because you're open to all of it. Joy, sadness, power, vulnerability — you can taste them all. This range is your richness.", question: "What experience has your openness allowed you to understand that others might miss?" },
      { title: "Boundaries for Open Systems", body: "As an open energy system, your boundaries need to be especially clear. Not walls — filters. Let the right energies in and keep the harmful ones out. You get to choose.", question: "What filter needs adjustment in your life right now?" },
      { title: "The Wise Wait", body: "28 days gives you access to every gate in the wheel. Each day brings a slightly different perspective on the same question. By the end of the cycle, you've seen it from every angle.", question: "What question are you sitting with that will become clearer over time?" },
      { title: "Nightly Clearing", body: "Before bed, imagine releasing every energy that isn't yours. The frustration that might be someone else's. The excitement that might be your environment's. Find what's genuinely yours underneath.", question: "What are you feeling right now that is truly yours versus absorbed?" },
      { title: "The Value of Difference", body: "Feeling different from everyone else isn't a problem — it's your design. You're not meant to fit in the same way others do. You're meant to reflect, evaluate, and mirror back what you see.", question: "Where are you trying to fit in instead of standing in your unique role?" },
      { title: "Environmental Audit", body: "Regularly evaluate your environments: home, work, social spaces, digital spaces. Each one affects you profoundly. Small adjustments to your surroundings can create massive shifts in your well-being.", question: "What one environmental change would make the biggest positive difference?" },
      { title: "The Surprise Strategy", body: "Plan less. Leave space for the unexpected. Your design thrives when there's room for surprise — for encounters, insights, and experiences you couldn't have predicted.", question: "How tightly are you controlling your schedule, and what would happen if you loosened it?" },
      { title: "Feeling Others", body: "You feel others deeply — their pain, their joy, their potential. This empathy is a gift, but it needs management. Feel it, reflect it, but don't carry it. It's theirs, not yours.", question: "Whose emotions are you carrying as if they were your own?" },
      { title: "The Patient Sage", body: "Your wisdom comes from patient observation over time. You see patterns that quick-decision-makers miss. Your slowness isn't weakness — it's thoroughness. Own it.", question: "What pattern have you noticed over time that others keep missing?" },
      { title: "Moon Tracking", body: "Consider tracking your mood, energy, and decisions alongside the lunar calendar. Over a few months, you'll discover your personal rhythm — the days you're best for decisions, rest, and creativity.", question: "Have you noticed any correlation between moon phases and your well-being?" },
      { title: "Evening Gratitude", body: "Tonight, be grateful for your openness. Yes, it makes life more complex. But it also makes it richer, deeper, and more textured than most people experience. You feel everything — and that's beautiful.", question: "What did your openness allow you to experience today that you're grateful for?" }
    ]
  }
}

// Generate translated versions - for non-EN languages, we use the EN structure
// but with translated content. This function handles fallback.
function getThoughtsForLang(lang) {
  if (THOUGHTS[lang]) return THOUGHTS[lang]
  // Fallback to English for languages not yet translated
  return THOUGHTS.en
}

/**
 * Get a daily thought based on HD type and language, rotating by day of year
 * @param {string} hdType - Human Design type
 * @param {string} lang - Language code  
 * @returns {{ title: string, body: string, question: string }}
 */
export function getDailyThought(hdType, lang = 'en') {
  const langData = getThoughtsForLang(lang)
  // Map MG to its own pool, fallback to Generator
  const typeData = langData[hdType] || langData['Generator']
  
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000
  )
  
  const index = dayOfYear % typeData.length
  return typeData[index]
}