// ─────────────────────────────────────────────────────────────
// TEXTELE PAGINII PRINCIPALE (LANDING) — 11 LIMBI
// Rescris integral (calup arhitectura 30.07, L1-L6) — structura si textul
// romanesc sunt STANDARDUL (regula 4). Celelalte 10 limbi: traducere nativa,
// nu literala — verificate cu incredere maxima doar RO/EN; restul merita
// o trecere de vorbitor nativ inainte de a fi considerate finale (regula 3).
// GCAO 01.08.2026 (A4): hero_spots_template (contor viu "primii 1.000") ELIMINAT
// complet, inlocuit cu hero_trial_line (proba de 3 zile, fara card, A5).
// pricing_body: scoasa mentiunea "gratuit pentru primii 1.000" — profilul e
// €4 pentru toata lumea, neschimbat (C.3); adaugata mentiunea probei.
// ─────────────────────────────────────────────────────────────

export const LANDING = {
  en: {
    nav_language_label: 'Language',
    hero_title: "You're living on fast-forward.",
    hero_sub: 'The place where you come back to yourself. Two moments a day, carried by water.',
    hero_cta: 'Start',
    hero_trial_line: '3 days of full access, free — no card needed.',
    hero_login: 'Already have an account? Sign in',
    get_title: 'What you get',
    card_profile_tag: 'The Profile',
    card_profile_text: 'A mirror of how you are built — astrology, Human Design, and numerology, explained like a human, no jargon.',
    card_ritual_tag: 'The Rituals',
    card_ritual_text: 'You leave the morning with direction. You fall asleep at night calmer than when you picked up your phone.',
    card_path_tag: 'The Path',
    card_path_text: '90 days in which the water changes state along with you. No scores, no penalties.',
    how_title: 'How it works',
    step1: 'You give your birth date, time, and place',
    step2: 'You receive your profile, written only for you',
    step3: 'You step into the daily rhythm.',
    pricing_title: 'The prices, upfront',
    pricing_body: 'The profile: €4, once. The subscription, if you want the whole path: €8/month or €80/year — 3 days free trial, no card needed. Compatibility with someone close to you: €8. 30-day guarantee, no questions asked.',
    langs_title: 'Written natively in 11 languages',
    final_1: "Life isn't about manifesting,",
    final_2: "it's about aligning with yourself.",
  },

  ro: {
    nav_language_label: 'Limbă',
    hero_title: 'Trăiești pe repede-înainte.',
    hero_sub: 'Locul unde te întorci la tine. Două momente pe zi, purtate de apă.',
    hero_cta: 'Începe',
    hero_trial_line: '3 zile de acces complet, gratuit — fără card.',
    hero_login: 'Ai deja cont? Intră',
    get_title: 'Ce primești',
    card_profile_tag: 'Profilul',
    card_profile_text: 'O oglindă a felului în care ești construit — astrologie, Human Design și numerologie, explicate omenește, fără jargon.',
    card_ritual_tag: 'Ritualurile',
    card_ritual_text: 'Dimineața pleci cu direcție. Seara adormi mai liniștit decât ai deschis telefonul.',
    card_path_tag: 'Drumul',
    card_path_text: '90 de zile în care apa își schimbă starea odată cu tine. Fără scoruri, fără pedepse.',
    how_title: 'Cum funcționează',
    step1: 'Îți dai data, ora și locul nașterii',
    step2: 'Primești profilul tău, scris doar pentru tine',
    step3: 'Intri în ritmul zilnic.',
    pricing_title: 'Prețurile, pe față',
    pricing_body: 'Profilul: €4, o singură dată. Abonamentul, dacă vrei drumul întreg: €8/lună sau €80/an — 3 zile de probă gratuită, fără card. Compatibilitatea cu cineva apropiat: €8. Garanție 30 de zile, fără întrebări.',
    langs_title: 'Scris nativ în 11 limbi',
    final_1: 'Viața nu e despre a manifesta,',
    final_2: 'e despre a te alinia cu tine însuți.',
  },

  es: {
    nav_language_label: 'Idioma',
    hero_title: 'Vives en avance rápido.',
    hero_sub: 'El lugar donde vuelves a ti. Dos momentos al día, llevados por el agua.',
    hero_cta: 'Empezar',
    hero_trial_line: '3 días de acceso completo, gratis — sin tarjeta.',
    hero_login: '¿Ya tienes cuenta? Entra',
    get_title: 'Lo que recibes',
    card_profile_tag: 'El Perfil',
    card_profile_text: 'Un espejo de cómo estás construido — astrología, Human Design y numerología, explicados de forma humana, sin jerga.',
    card_ritual_tag: 'Los Rituales',
    card_ritual_text: 'Empiezas la mañana con dirección. Te duermes por la noche más tranquilo que cuando cogiste el móvil.',
    card_path_tag: 'El Camino',
    card_path_text: '90 días en los que el agua cambia de estado junto contigo. Sin puntuaciones, sin penalizaciones.',
    how_title: 'Cómo funciona',
    step1: 'Das tu fecha, hora y lugar de nacimiento',
    step2: 'Recibes tu perfil, escrito solo para ti',
    step3: 'Entras en el ritmo diario.',
    pricing_title: 'Los precios, claros',
    pricing_body: 'El perfil: €4, una sola vez. La suscripción, si quieres el camino completo: €8/mes o €80/año — 3 días de prueba gratis, sin tarjeta. La compatibilidad con alguien cercano: €8. Garantía de 30 días, sin preguntas.',
    langs_title: 'Escrito de forma nativa en 11 idiomas',
    final_1: 'La vida no se trata de manifestar,',
    final_2: 'se trata de alinearte contigo mismo.',
  },

  fr: {
    nav_language_label: 'Langue',
    hero_title: 'Tu vis en avance rapide.',
    hero_sub: "L'endroit où tu reviens à toi-même. Deux moments par jour, portés par l'eau.",
    hero_cta: 'Commencer',
    hero_trial_line: '3 jours d\'accès complet, gratuit — sans carte.',
    hero_login: 'Tu as déjà un compte ? Connecte-toi',
    get_title: 'Ce que tu reçois',
    card_profile_tag: 'Le Profil',
    card_profile_text: "Un miroir de la façon dont tu es construit — astrologie, Human Design et numérologie, expliqués simplement, sans jargon.",
    card_ritual_tag: 'Les Rituels',
    card_ritual_text: 'Tu pars le matin avec une direction. Tu t\'endors le soir plus calme que quand tu as pris ton téléphone.',
    card_path_tag: 'Le Chemin',
    card_path_text: "90 jours pendant lesquels l'eau change d'état en même temps que toi. Sans scores, sans pénalités.",
    how_title: 'Comment ça marche',
    step1: 'Tu donnes ta date, heure et lieu de naissance',
    step2: 'Tu reçois ton profil, écrit rien que pour toi',
    step3: 'Tu entres dans le rythme quotidien.',
    pricing_title: 'Les prix, sans détour',
    pricing_body: "Le profil : 4 €, une seule fois. L'abonnement, si tu veux le chemin complet : 8 €/mois ou 80 €/an — 3 jours d'essai gratuit, sans carte. La compatibilité avec un proche : 8 €. Garantie 30 jours, sans question.",
    langs_title: 'Écrit nativement en 11 langues',
    final_1: "La vie, ce n'est pas manifester,",
    final_2: "c'est s'aligner avec soi-même.",
  },

  de: {
    nav_language_label: 'Sprache',
    hero_title: 'Du lebst im Schnellvorlauf.',
    hero_sub: 'Der Ort, an dem du zu dir zurückkehrst. Zwei Momente am Tag, getragen vom Wasser.',
    hero_cta: 'Starten',
    hero_trial_line: '3 Tage voller Zugang, kostenlos — ohne Karte.',
    hero_login: 'Schon ein Konto? Anmelden',
    get_title: 'Was du bekommst',
    card_profile_tag: 'Das Profil',
    card_profile_text: 'Ein Spiegel dessen, wie du gebaut bist — Astrologie, Human Design und Numerologie, menschlich erklärt, ohne Fachjargon.',
    card_ritual_tag: 'Die Rituale',
    card_ritual_text: 'Du startest den Morgen mit Richtung. Abends schläfst du ruhiger ein, als du dein Handy in die Hand genommen hast.',
    card_path_tag: 'Der Weg',
    card_path_text: '90 Tage, in denen sich das Wasser mit dir verändert. Keine Punkte, keine Strafen.',
    how_title: 'So funktioniert es',
    step1: 'Du gibst Geburtsdatum, -zeit und -ort ein',
    step2: 'Du erhältst dein Profil, geschrieben nur für dich',
    step3: 'Du kommst in den täglichen Rhythmus.',
    pricing_title: 'Die Preise, offen gelegt',
    pricing_body: 'Das Profil: 4 €, einmalig. Das Abo, wenn du den ganzen Weg willst: 8 €/Monat oder 80 €/Jahr — 3 Tage kostenlose Testphase, ohne Karte. Die Kompatibilität mit jemandem, der dir nahesteht: 8 €. 30 Tage Garantie, ohne Fragen.',
    langs_title: 'Nativ geschrieben in 11 Sprachen',
    final_1: 'Im Leben geht es nicht ums Manifestieren,',
    final_2: 'es geht darum, dich mit dir selbst auszurichten.',
  },

  it: {
    nav_language_label: 'Lingua',
    hero_title: 'Vivi in avanti veloce.',
    hero_sub: "Il posto dove torni a te stesso. Due momenti al giorno, portati dall'acqua.",
    hero_cta: 'Inizia',
    hero_trial_line: '3 giorni di accesso completo, gratis — senza carta.',
    hero_login: 'Hai già un account? Accedi',
    get_title: 'Cosa ricevi',
    card_profile_tag: 'Il Profilo',
    card_profile_text: 'Uno specchio di come sei fatto — astrologia, Human Design e numerologia, spiegati in modo umano, senza gergo.',
    card_ritual_tag: 'I Rituali',
    card_ritual_text: 'Parti al mattino con una direzione. La sera ti addormenti più calmo di quando hai preso in mano il telefono.',
    card_path_tag: 'Il Cammino',
    card_path_text: "90 giorni in cui l'acqua cambia stato insieme a te. Niente punteggi, niente penalità.",
    how_title: 'Come funziona',
    step1: 'Dai data, ora e luogo di nascita',
    step2: 'Ricevi il tuo profilo, scritto solo per te',
    step3: 'Entri nel ritmo quotidiano.',
    pricing_title: 'I prezzi, in chiaro',
    pricing_body: 'Il profilo: 4 €, una sola volta. L\'abbonamento, se vuoi il cammino intero: 8 €/mese o 80 €/anno — 3 giorni di prova gratuita, senza carta. La compatibilità con una persona vicina: 8 €. Garanzia di 30 giorni, senza domande.',
    langs_title: 'Scritto in modo nativo in 11 lingue',
    final_1: 'La vita non è manifestare,',
    final_2: 'è allinearti con te stesso.',
  },

  pt: {
    nav_language_label: 'Idioma',
    hero_title: 'Vives em avanço rápido.',
    hero_sub: 'O lugar onde voltas a ti. Dois momentos por dia, levados pela água.',
    hero_cta: 'Começar',
    hero_trial_line: '3 dias de acesso completo, grátis — sem cartão.',
    hero_login: 'Já tens conta? Entra',
    get_title: 'O que recebes',
    card_profile_tag: 'O Perfil',
    card_profile_text: 'Um espelho de como és construído — astrologia, Human Design e numerologia, explicados de forma humana, sem jargão.',
    card_ritual_tag: 'Os Rituais',
    card_ritual_text: 'Começas a manhã com direção. Adormeces à noite mais calmo do que quando pegaste no telemóvel.',
    card_path_tag: 'O Caminho',
    card_path_text: '90 dias em que a água muda de estado junto contigo. Sem pontuações, sem penalizações.',
    how_title: 'Como funciona',
    step1: 'Dás a tua data, hora e local de nascimento',
    step2: 'Recebes o teu perfil, escrito só para ti',
    step3: 'Entras no ritmo diário.',
    pricing_title: 'Os preços, à vista',
    pricing_body: 'O perfil: €4, uma única vez. A subscrição, se quiseres o caminho todo: €8/mês ou €80/ano — 3 dias de teste grátis, sem cartão. A compatibilidade com alguém próximo: €8. Garantia de 30 dias, sem perguntas.',
    langs_title: 'Escrito de forma nativa em 11 idiomas',
    final_1: 'A vida não é sobre manifestar,',
    final_2: 'é sobre te alinhares contigo mesmo.',
  },

  nl: {
    nav_language_label: 'Taal',
    hero_title: 'Je leeft in snel-vooruit.',
    hero_sub: 'De plek waar je terugkeert naar jezelf. Twee momenten per dag, gedragen door water.',
    hero_cta: 'Begin',
    hero_trial_line: '3 dagen volledige toegang, gratis — zonder kaart.',
    hero_login: 'Heb je al een account? Log in',
    get_title: 'Wat je krijgt',
    card_profile_tag: 'Het Profiel',
    card_profile_text: 'Een spiegel van hoe je in elkaar zit — astrologie, Human Design en numerologie, menselijk uitgelegd, zonder jargon.',
    card_ritual_tag: 'De Rituelen',
    card_ritual_text: "'s Ochtends vertrek je met richting. 's Avonds val je rustiger in slaap dan toen je je telefoon oppakte.",
    card_path_tag: 'De Weg',
    card_path_text: '90 dagen waarin het water met je meeverandert. Geen scores, geen straffen.',
    how_title: 'Hoe het werkt',
    step1: 'Je geeft je geboortedatum, -tijd en -plaats',
    step2: 'Je ontvangt je profiel, alleen voor jou geschreven',
    step3: 'Je stapt in het dagelijkse ritme.',
    pricing_title: 'De prijzen, open en eerlijk',
    pricing_body: 'Het profiel: €4, eenmalig. Het abonnement, als je de hele weg wilt: €8/maand of €80/jaar — 3 dagen gratis proefperiode, zonder kaart. Compatibiliteit met iemand die je na staat: €8. 30 dagen garantie, geen vragen.',
    langs_title: 'Nativ geschreven in 11 talen',
    final_1: 'Het leven gaat niet over manifesteren,',
    final_2: 'het gaat over jezelf uitlijnen met wie je bent.',
  },

  pl: {
    nav_language_label: 'Język',
    hero_title: 'Żyjesz na przewijaniu do przodu.',
    hero_sub: 'Miejsce, w którym wracasz do siebie. Dwie chwile dziennie, niesione przez wodę.',
    hero_cta: 'Zacznij',
    hero_trial_line: '3 dni pełnego dostępu, za darmo — bez karty.',
    hero_login: 'Masz już konto? Zaloguj się',
    get_title: 'Co otrzymujesz',
    card_profile_tag: 'Profil',
    card_profile_text: 'Lustro tego, jak jesteś zbudowany — astrologia, Human Design i numerologia, wyjaśnione po ludzku, bez żargonu.',
    card_ritual_tag: 'Rytuały',
    card_ritual_text: 'Rano wychodzisz z kierunkiem. Wieczorem zasypiasz spokojniejszy niż w chwili, gdy wziąłeś telefon do ręki.',
    card_path_tag: 'Droga',
    card_path_text: '90 dni, w których woda zmienia stan razem z tobą. Bez punktów, bez kar.',
    how_title: 'Jak to działa',
    step1: 'Podajesz datę, godzinę i miejsce urodzenia',
    step2: 'Otrzymujesz swój profil, napisany tylko dla ciebie',
    step3: 'Wchodzisz w codzienny rytm.',
    pricing_title: 'Ceny, wprost',
    pricing_body: 'Profil: 4 €, jednorazowo. Subskrypcja, jeśli chcesz całą drogę: 8 €/miesiąc lub 80 €/rok — 3 dni bezpłatnego okresu próbnego, bez karty. Kompatybilność z kimś bliskim: 8 €. Gwarancja zwrotu 30 dni, bez pytań.',
    langs_title: 'Napisane natywnie w 11 językach',
    final_1: 'Życie nie polega na manifestowaniu,',
    final_2: 'polega na wyrównaniu się z samym sobą.',
  },

  hu: {
    nav_language_label: 'Nyelv',
    hero_title: 'Gyorsított tempóban élsz.',
    hero_sub: 'A hely, ahol visszatalálsz önmagadhoz. Napi két pillanat, a víz hordozásában.',
    hero_cta: 'Kezdés',
    hero_trial_line: '3 nap teljes hozzáférés, ingyen — kártya nélkül.',
    hero_login: 'Már van fiókod? Jelentkezz be',
    get_title: 'Amit kapsz',
    card_profile_tag: 'A Profil',
    card_profile_text: 'Tükör arról, hogyan épülsz fel — asztrológia, Human Design és numerológia, emberi módon elmagyarázva, szakzsargon nélkül.',
    card_ritual_tag: 'A Rituálék',
    card_ritual_text: 'Reggel iránnyal indulsz. Este nyugodtabban alszol el, mint amikor felvetted a telefonod.',
    card_path_tag: 'Az Út',
    card_path_text: '90 nap, amely alatt a víz veled együtt változtatja állapotát. Nincs pontszám, nincs büntetés.',
    how_title: 'Hogyan működik',
    step1: 'Megadod a születési dátumod, időpontod és helyed',
    step2: 'Megkapod a profilodat, kizárólag neked megírva',
    step3: 'Belépsz a napi ritmusba.',
    pricing_title: 'Az árak, nyíltan',
    pricing_body: 'A profil: 4 €, egyszeri. Az előfizetés, ha a teljes utat szeretnéd: 8 €/hónap vagy 80 €/év — 3 nap ingyenes próbaidőszak, kártya nélkül. A kompatibilitás valakivel, aki közel áll hozzád: 8 €. 30 napos garancia, kérdés nélkül.',
    langs_title: 'Natívan megírva 11 nyelven',
    final_1: 'Az élet nem a manifesztálásról szól,',
    final_2: 'hanem arról, hogy összhangba kerülj önmagaddal.',
  },

  ru: {
    nav_language_label: 'Язык',
    hero_title: 'Ты живёшь в режиме перемотки вперёд.',
    hero_sub: 'Место, где ты возвращаешься к себе. Два момента в день, несомые водой.',
    hero_cta: 'Начать',
    hero_trial_line: '3 дня полного доступа, бесплатно — без карты.',
    hero_login: 'Уже есть аккаунт? Войти',
    get_title: 'Что ты получаешь',
    card_profile_tag: 'Профиль',
    card_profile_text: 'Зеркало того, как ты устроен — астрология, Human Design и нумерология, объяснённые по-человечески, без жаргона.',
    card_ritual_tag: 'Ритуалы',
    card_ritual_text: 'Утром ты выходишь с направлением. Вечером ты засыпаешь спокойнее, чем когда взял в руки телефон.',
    card_path_tag: 'Путь',
    card_path_text: '90 дней, в течение которых вода меняет своё состояние вместе с тобой. Без баллов, без штрафов.',
    how_title: 'Как это работает',
    step1: 'Ты указываешь дату, время и место рождения',
    step2: 'Ты получаешь свой профиль, написанный только для тебя',
    step3: 'Ты входишь в ежедневный ритм.',
    pricing_title: 'Цены — открыто',
    pricing_body: 'Профиль: 4 €, единоразово. Подписка, если хочешь весь путь: 8 €/месяц или 80 €/год — 3 дня бесплатного пробного периода, без карты. Совместимость с близким человеком: 8 €. Гарантия возврата 30 дней, без вопросов.',
    langs_title: 'Написано на языке оригинала на 11 языках',
    final_1: 'Жизнь — это не про то, чтобы манифестировать,',
    final_2: 'а про то, чтобы быть в согласии с собой.',
  },
}

export function lt(language, key) {
  const lang = LANDING[language] || LANDING['en']
  return lang[key] !== undefined ? lang[key] : (LANDING['en'][key] !== undefined ? LANDING['en'][key] : key)
}
