// ─────────────────────────────────────────────────────────────
// TEXTELE PAGINII PRINCIPALE (LANDING) — 10 LIMBI
// Fișier separat de translations.js, ca să nu atingem nimic acolo.
// Conținut = textele actuale, traduse fidel. Rescrierea inspirațională
// (proces + aliniere, ton 3) se face aici, o singură dată, mai târziu.
// Destinație: lib/landing.js  (FIȘIER NOU)
// ─────────────────────────────────────────────────────────────

export const LANDING = {
  en: {
    nav_start: 'Start',
    banner_back: '✦ Welcome back — your profile is waiting',
    banner_view: 'View My Profile →',
    hero_title_1: 'When you align with yourself',
    hero_title_2: 'everything else follows.',
    hero_sub: 'Human Design. Astrology. Numerology. One profile that finally tells you who you are — and a daily ritual to live it.',
    hero_cta: 'Start Here',
    hero_cta_note: 'Free. No card. 30 seconds.',
    get_title: 'What you actually get',
    get_sub: 'Four pieces, designed to work together. Built around who you are — not generic advice.',
    card_profile_tag: 'Profile',
    card_profile_title: 'Your unique profile',
    card_profile_text: 'Human Design, astrology, and numerology synthesized into one honest document. Personal. Specific. Yours.',
    card_ritual_tag: 'Daily Ritual',
    card_ritual_title: '2-minute daily ritual',
    card_ritual_text: 'A short check-in. Real questions. Your alignment, tracked over time without ever feeling like a chore.',
    card_patterns_tag: 'Patterns',
    card_patterns_title: 'Patterns that guide you',
    card_patterns_text: "Streaks, weekly reviews, and pattern detection that learns from you — not from some generic app's idea of progress.",
    card_foundation_tag: 'Foundation',
    card_foundation_title: 'Built on who you are',
    card_foundation_text: 'Three ancient systems, calculated from your birth data, woven into one contemporary profile you can actually use.',
    pillar_astro: 'Astrology',
    pillar_num: 'Numerology',
    trust_banner: 'No subscription. No card. Your profile is free.',
    trust_private: 'Private & secure',
    trust_fast: 'Ready in 2 minutes',
    trust_langs: '10 languages',
    how_title: 'How it works',
    step1_title: 'Enter your birth data',
    step1_text: 'Name, date, time, and city of birth. This is how your unique profile is calculated.',
    step2_title: 'Receive your profile',
    step2_text: 'In 2-3 minutes, your personal profile is generated — warm, honest, and structured.',
    step3_title: 'Start the path',
    step3_text: 'Read your profile. Start your plan. Check in daily. The rest unfolds from there.',
    pricing_title: 'Clear pricing. No surprises.',
    pricing_sub: "Start free. Upgrade only if it's worth it.",
    price_free_tag: 'Profile',
    price_free: 'Free',
    price_free_note: 'Yours to keep',
    price_free_desc: 'Your full personal profile — Human Design, astrology, and numerology combined into one document. Includes your alignment plan.',
    price_free_btn: 'Get Your Profile →',
    price_premium_tag: 'Full Path',
    price_month: '/month',
    price_annual: 'or €80/year — 2 months free',
    features: [
      'Everything in the free profile',
      'Daily 2-minute check-in ritual',
      'Weekly pattern detection & reviews',
      'Streaks, score, and gentle accountability',
      'Available in 10 languages',
    ],
    price_premium_btn: 'Start Your Path',
    guarantee: '🛡 30-day money-back guarantee · Cancel anytime',
    final_1: 'The most honest relationship you will',
    final_2: 'ever have is the one with yourself.',
    footer_text: 'Available in 10 languages. Built for people who are done with generic advice.',
    free_tag: 'Free Profile',
  },

  ro: {
    nav_start: 'Începe',
    banner_back: '✦ Bine ai revenit — profilul tău te așteaptă',
    banner_view: 'Vezi profilul meu →',
    hero_title_1: 'Când te aliniezi cu tine,',
    hero_title_2: 'restul vine de la sine.',
    hero_sub: 'Human Design. Astrologie. Numerologie. Un profil care îți spune, în sfârșit, cine ești — și un ritual zilnic prin care să-l trăiești.',
    hero_cta: 'Începe aici',
    hero_cta_note: 'Gratuit. Fără card. 30 de secunde.',
    get_title: 'Ce primești, concret',
    get_sub: 'Patru piese, gândite să lucreze împreună. Construite în jurul a cine ești — nu sfaturi generice.',
    card_profile_tag: 'Profil',
    card_profile_title: 'Profilul tău unic',
    card_profile_text: 'Human Design, astrologie și numerologie, sintetizate într-un document onest. Personal. Specific. Al tău.',
    card_ritual_tag: 'Ritual zilnic',
    card_ritual_title: 'Ritual zilnic de 2 minute',
    card_ritual_text: 'Un check-in scurt. Întrebări reale. Alinierea ta, urmărită în timp, fără să devină vreodată o corvoadă.',
    card_patterns_tag: 'Tipare',
    card_patterns_title: 'Tipare care te ghidează',
    card_patterns_text: 'Serii, recapitulări săptămânale și tipare detectate care învață de la tine — nu de la ideea de progres a unei aplicații generice.',
    card_foundation_tag: 'Fundație',
    card_foundation_title: 'Construit pe cine ești',
    card_foundation_text: 'Trei sisteme vechi, calculate din datele tale de naștere, țesute într-un profil contemporan pe care chiar îl poți folosi.',
    pillar_astro: 'Astrologie',
    pillar_num: 'Numerologie',
    trust_banner: 'Fără abonament. Fără card. Profilul tău e gratuit.',
    trust_private: 'Privat și securizat',
    trust_fast: 'Gata în 2 minute',
    trust_langs: '10 limbi',
    how_title: 'Cum funcționează',
    step1_title: 'Introdu datele de naștere',
    step1_text: 'Nume, dată, oră și orașul nașterii. Așa se calculează profilul tău unic.',
    step2_title: 'Primești profilul',
    step2_text: 'În 2-3 minute, profilul tău personal e generat — cald, onest și structurat.',
    step3_title: 'Începe drumul',
    step3_text: 'Citește profilul. Pornește planul. Fă check-in zilnic. Restul se desfășoară de acolo.',
    pricing_title: 'Prețuri clare. Fără surprize.',
    pricing_sub: 'Începe gratuit. Mergi mai departe doar dacă merită.',
    price_free_tag: 'Profil',
    price_free: 'Gratuit',
    price_free_note: 'Al tău, pentru totdeauna',
    price_free_desc: 'Profilul tău personal complet — Human Design, astrologie și numerologie combinate într-un singur document. Include planul tău de aliniere.',
    price_free_btn: 'Obține profilul →',
    price_premium_tag: 'Drumul complet',
    price_month: '/lună',
    price_annual: 'sau €80/an — 2 luni gratuite',
    features: [
      'Tot ce e în profilul gratuit',
      'Ritual zilnic de check-in de 2 minute',
      'Detectare de tipare și recapitulări săptămânale',
      'Serii, scor și responsabilitate blândă',
      'Disponibil în 10 limbi',
    ],
    price_premium_btn: 'Pornește pe drumul tău',
    guarantee: '🛡 Garanție 30 de zile — banii înapoi · Anulezi oricând',
    final_1: 'Cea mai onestă relație pe care o vei avea vreodată',
    final_2: 'este cea cu tine însuți.',
    footer_text: 'Disponibil în 10 limbi. Făcut pentru oameni care au terminat-o cu sfaturile generice.',
    free_tag: 'Profil gratuit',
  },

  es: {
    nav_start: 'Empezar',
    banner_back: '✦ Bienvenido de nuevo — tu perfil te espera',
    banner_view: 'Ver mi perfil →',
    hero_title_1: 'Cuando te alineas contigo,',
    hero_title_2: 'todo lo demás llega solo.',
    hero_sub: 'Human Design. Astrología. Numerología. Un perfil que por fin te dice quién eres — y un ritual diario para vivirlo.',
    hero_cta: 'Empieza aquí',
    hero_cta_note: 'Gratis. Sin tarjeta. 30 segundos.',
    get_title: 'Lo que realmente recibes',
    get_sub: 'Cuatro piezas diseñadas para funcionar juntas. Construidas en torno a quién eres — no consejos genéricos.',
    card_profile_tag: 'Perfil',
    card_profile_title: 'Tu perfil único',
    card_profile_text: 'Human Design, astrología y numerología sintetizados en un documento honesto. Personal. Específico. Tuyo.',
    card_ritual_tag: 'Ritual diario',
    card_ritual_title: 'Ritual diario de 2 minutos',
    card_ritual_text: 'Un check-in breve. Preguntas reales. Tu alineación, registrada en el tiempo sin sentirse nunca una obligación.',
    card_patterns_tag: 'Patrones',
    card_patterns_title: 'Patrones que te guían',
    card_patterns_text: 'Rachas, revisiones semanales y detección de patrones que aprende de ti — no de la idea de progreso de una app genérica.',
    card_foundation_tag: 'Fundamento',
    card_foundation_title: 'Construido sobre quién eres',
    card_foundation_text: 'Tres sistemas antiguos, calculados a partir de tus datos de nacimiento, tejidos en un perfil contemporáneo que realmente puedes usar.',
    pillar_astro: 'Astrología',
    pillar_num: 'Numerología',
    trust_banner: 'Sin suscripción. Sin tarjeta. Tu perfil es gratis.',
    trust_private: 'Privado y seguro',
    trust_fast: 'Listo en 2 minutos',
    trust_langs: '10 idiomas',
    how_title: 'Cómo funciona',
    step1_title: 'Ingresa tus datos de nacimiento',
    step1_text: 'Nombre, fecha, hora y ciudad de nacimiento. Así se calcula tu perfil único.',
    step2_title: 'Recibe tu perfil',
    step2_text: 'En 2-3 minutos se genera tu perfil personal — cálido, honesto y estructurado.',
    step3_title: 'Comienza el camino',
    step3_text: 'Lee tu perfil. Inicia tu plan. Haz check-in a diario. El resto se despliega desde ahí.',
    pricing_title: 'Precios claros. Sin sorpresas.',
    pricing_sub: 'Empieza gratis. Mejora solo si vale la pena.',
    price_free_tag: 'Perfil',
    price_free: 'Gratis',
    price_free_note: 'Tuyo para siempre',
    price_free_desc: 'Tu perfil personal completo — Human Design, astrología y numerología combinados en un solo documento. Incluye tu plan de alineación.',
    price_free_btn: 'Obtén tu perfil →',
    price_premium_tag: 'Camino completo',
    price_month: '/mes',
    price_annual: 'o €80/año — 2 meses gratis',
    features: [
      'Todo lo del perfil gratuito',
      'Ritual diario de check-in de 2 minutos',
      'Detección de patrones y revisiones semanales',
      'Rachas, puntuación y responsabilidad amable',
      'Disponible en 10 idiomas',
    ],
    price_premium_btn: 'Comienza tu camino',
    guarantee: '🛡 Garantía de devolución de 30 días · Cancela cuando quieras',
    final_1: 'La relación más honesta que tendrás jamás',
    final_2: 'es la que tienes contigo mismo.',
    footer_text: 'Disponible en 10 idiomas. Hecho para personas que ya no quieren consejos genéricos.',
    free_tag: 'Perfil gratuito',
  },

  fr: {
    nav_start: 'Commencer',
    banner_back: "✦ Bon retour — ton profil t'attend",
    banner_view: 'Voir mon profil →',
    hero_title_1: "Quand tu t'alignes avec toi-même,",
    hero_title_2: 'tout le reste suit.',
    hero_sub: 'Human Design. Astrologie. Numérologie. Un profil qui te dit enfin qui tu es — et un rituel quotidien pour le vivre.',
    hero_cta: 'Commence ici',
    hero_cta_note: 'Gratuit. Sans carte. 30 secondes.',
    get_title: 'Ce que tu reçois vraiment',
    get_sub: 'Quatre pièces conçues pour fonctionner ensemble. Construites autour de qui tu es — pas de conseils génériques.',
    card_profile_tag: 'Profil',
    card_profile_title: 'Ton profil unique',
    card_profile_text: 'Human Design, astrologie et numérologie synthétisés en un document honnête. Personnel. Précis. Le tien.',
    card_ritual_tag: 'Rituel quotidien',
    card_ritual_title: 'Rituel quotidien de 2 minutes',
    card_ritual_text: 'Un court check-in. De vraies questions. Ton alignement, suivi dans le temps sans jamais devenir une corvée.',
    card_patterns_tag: 'Schémas',
    card_patterns_title: 'Des schémas qui te guident',
    card_patterns_text: "Séries, bilans hebdomadaires et détection de schémas qui apprend de toi — pas de l'idée du progrès d'une app générique.",
    card_foundation_tag: 'Fondation',
    card_foundation_title: 'Construit sur qui tu es',
    card_foundation_text: 'Trois systèmes anciens, calculés à partir de tes données de naissance, tissés en un profil contemporain que tu peux vraiment utiliser.',
    pillar_astro: 'Astrologie',
    pillar_num: 'Numérologie',
    trust_banner: "Pas d'abonnement. Pas de carte. Ton profil est gratuit.",
    trust_private: 'Privé et sécurisé',
    trust_fast: 'Prêt en 2 minutes',
    trust_langs: '10 langues',
    how_title: 'Comment ça marche',
    step1_title: 'Entre tes données de naissance',
    step1_text: "Nom, date, heure et ville de naissance. C'est ainsi que ton profil unique est calculé.",
    step2_title: 'Reçois ton profil',
    step2_text: 'En 2-3 minutes, ton profil personnel est généré — chaleureux, honnête et structuré.',
    step3_title: 'Commence le chemin',
    step3_text: 'Lis ton profil. Lance ton plan. Fais ton check-in chaque jour. Le reste se déploie de là.',
    pricing_title: 'Des prix clairs. Sans surprises.',
    pricing_sub: "Commence gratuitement. Va plus loin seulement si ça en vaut la peine.",
    price_free_tag: 'Profil',
    price_free: 'Gratuit',
    price_free_note: 'À toi pour toujours',
    price_free_desc: "Ton profil personnel complet — Human Design, astrologie et numérologie réunis en un seul document. Inclut ton plan d'alignement.",
    price_free_btn: 'Obtiens ton profil →',
    price_premium_tag: 'Chemin complet',
    price_month: '/mois',
    price_annual: 'ou €80/an — 2 mois offerts',
    features: [
      'Tout ce qui est dans le profil gratuit',
      'Rituel quotidien de check-in de 2 minutes',
      'Détection de schémas et bilans hebdomadaires',
      'Séries, score et responsabilité bienveillante',
      'Disponible en 10 langues',
    ],
    price_premium_btn: 'Commence ton chemin',
    guarantee: '🛡 Garantie satisfait ou remboursé 30 jours · Annulable à tout moment',
    final_1: 'La relation la plus honnête que tu auras jamais',
    final_2: 'est celle avec toi-même.',
    footer_text: 'Disponible en 10 langues. Conçu pour ceux qui en ont fini avec les conseils génériques.',
    free_tag: 'Profil gratuit',
  },

  de: {
    nav_start: 'Starten',
    banner_back: '✦ Willkommen zurück — dein Profil wartet auf dich',
    banner_view: 'Mein Profil ansehen →',
    hero_title_1: 'Wenn du dich mit dir selbst ausrichtest,',
    hero_title_2: 'folgt alles andere von selbst.',
    hero_sub: 'Human Design. Astrologie. Numerologie. Ein Profil, das dir endlich sagt, wer du bist — und ein tägliches Ritual, um es zu leben.',
    hero_cta: 'Starte hier',
    hero_cta_note: 'Kostenlos. Keine Karte. 30 Sekunden.',
    get_title: 'Was du wirklich bekommst',
    get_sub: 'Vier Teile, die zusammenwirken. Gebaut um das, was du bist — keine generischen Ratschläge.',
    card_profile_tag: 'Profil',
    card_profile_title: 'Dein einzigartiges Profil',
    card_profile_text: 'Human Design, Astrologie und Numerologie zu einem ehrlichen Dokument verbunden. Persönlich. Konkret. Deins.',
    card_ritual_tag: 'Tägliches Ritual',
    card_ritual_title: '2-Minuten-Ritual täglich',
    card_ritual_text: 'Ein kurzer Check-in. Echte Fragen. Deine Ausrichtung, über die Zeit verfolgt, ohne je zur Pflicht zu werden.',
    card_patterns_tag: 'Muster',
    card_patterns_title: 'Muster, die dich leiten',
    card_patterns_text: 'Streaks, wöchentliche Rückblicke und Mustererkennung, die von dir lernt — nicht von der Fortschrittsidee einer generischen App.',
    card_foundation_tag: 'Fundament',
    card_foundation_title: 'Gebaut auf dem, was du bist',
    card_foundation_text: 'Drei alte Systeme, aus deinen Geburtsdaten berechnet, zu einem zeitgemäßen Profil verwoben, das du wirklich nutzen kannst.',
    pillar_astro: 'Astrologie',
    pillar_num: 'Numerologie',
    trust_banner: 'Kein Abo. Keine Karte. Dein Profil ist kostenlos.',
    trust_private: 'Privat und sicher',
    trust_fast: 'Fertig in 2 Minuten',
    trust_langs: '10 Sprachen',
    how_title: 'So funktioniert es',
    step1_title: 'Gib deine Geburtsdaten ein',
    step1_text: 'Name, Datum, Uhrzeit und Geburtsstadt. So wird dein einzigartiges Profil berechnet.',
    step2_title: 'Erhalte dein Profil',
    step2_text: 'In 2-3 Minuten wird dein persönliches Profil erstellt — warm, ehrlich und strukturiert.',
    step3_title: 'Beginne den Weg',
    step3_text: 'Lies dein Profil. Starte deinen Plan. Mach täglich deinen Check-in. Der Rest entfaltet sich von dort.',
    pricing_title: 'Klare Preise. Keine Überraschungen.',
    pricing_sub: 'Starte kostenlos. Upgrade nur, wenn es sich lohnt.',
    price_free_tag: 'Profil',
    price_free: 'Kostenlos',
    price_free_note: 'Für immer deins',
    price_free_desc: 'Dein vollständiges persönliches Profil — Human Design, Astrologie und Numerologie in einem Dokument vereint. Inklusive deines Ausrichtungsplans.',
    price_free_btn: 'Hol dir dein Profil →',
    price_premium_tag: 'Der ganze Weg',
    price_month: '/Monat',
    price_annual: 'oder €80/Jahr — 2 Monate geschenkt',
    features: [
      'Alles aus dem kostenlosen Profil',
      'Tägliches 2-Minuten-Check-in-Ritual',
      'Mustererkennung und wöchentliche Rückblicke',
      'Streaks, Score und sanfte Verbindlichkeit',
      'Verfügbar in 10 Sprachen',
    ],
    price_premium_btn: 'Beginne deinen Weg',
    guarantee: '🛡 30 Tage Geld-zurück-Garantie · Jederzeit kündbar',
    final_1: 'Die ehrlichste Beziehung, die du je haben wirst,',
    final_2: 'ist die mit dir selbst.',
    footer_text: 'Verfügbar in 10 Sprachen. Für Menschen, die genug von generischen Ratschlägen haben.',
    free_tag: 'Kostenloses Profil',
  },

  it: {
    nav_start: 'Inizia',
    banner_back: '✦ Bentornato — il tuo profilo ti aspetta',
    banner_view: 'Vedi il mio profilo →',
    hero_title_1: 'Quando ti allinei con te stesso,',
    hero_title_2: 'tutto il resto viene da sé.',
    hero_sub: 'Human Design. Astrologia. Numerologia. Un profilo che finalmente ti dice chi sei — e un rituale quotidiano per viverlo.',
    hero_cta: 'Inizia qui',
    hero_cta_note: 'Gratis. Senza carta. 30 secondi.',
    get_title: 'Cosa ricevi davvero',
    get_sub: 'Quattro pezzi pensati per lavorare insieme. Costruiti intorno a chi sei — non consigli generici.',
    card_profile_tag: 'Profilo',
    card_profile_title: 'Il tuo profilo unico',
    card_profile_text: 'Human Design, astrologia e numerologia sintetizzati in un documento onesto. Personale. Specifico. Tuo.',
    card_ritual_tag: 'Rituale quotidiano',
    card_ritual_title: 'Rituale quotidiano di 2 minuti',
    card_ritual_text: 'Un breve check-in. Domande vere. Il tuo allineamento, seguito nel tempo senza mai diventare un peso.',
    card_patterns_tag: 'Schemi',
    card_patterns_title: 'Schemi che ti guidano',
    card_patterns_text: "Serie, revisioni settimanali e rilevamento di schemi che impara da te — non dall'idea di progresso di un'app generica.",
    card_foundation_tag: 'Fondamento',
    card_foundation_title: 'Costruito su chi sei',
    card_foundation_text: 'Tre sistemi antichi, calcolati dai tuoi dati di nascita, intrecciati in un profilo contemporaneo che puoi davvero usare.',
    pillar_astro: 'Astrologia',
    pillar_num: 'Numerologia',
    trust_banner: 'Nessun abbonamento. Nessuna carta. Il tuo profilo è gratuito.',
    trust_private: 'Privato e sicuro',
    trust_fast: 'Pronto in 2 minuti',
    trust_langs: '10 lingue',
    how_title: 'Come funziona',
    step1_title: 'Inserisci i tuoi dati di nascita',
    step1_text: 'Nome, data, ora e città di nascita. Così viene calcolato il tuo profilo unico.',
    step2_title: 'Ricevi il tuo profilo',
    step2_text: 'In 2-3 minuti il tuo profilo personale viene generato — caldo, onesto e strutturato.',
    step3_title: 'Inizia il cammino',
    step3_text: 'Leggi il tuo profilo. Avvia il tuo piano. Fai il check-in ogni giorno. Il resto si dispiega da lì.',
    pricing_title: 'Prezzi chiari. Nessuna sorpresa.',
    pricing_sub: 'Inizia gratis. Vai oltre solo se ne vale la pena.',
    price_free_tag: 'Profilo',
    price_free: 'Gratis',
    price_free_note: 'Tuo per sempre',
    price_free_desc: 'Il tuo profilo personale completo — Human Design, astrologia e numerologia uniti in un solo documento. Include il tuo piano di allineamento.',
    price_free_btn: 'Ottieni il tuo profilo →',
    price_premium_tag: 'Il cammino completo',
    price_month: '/mese',
    price_annual: 'o €80/anno — 2 mesi gratis',
    features: [
      'Tutto ciò che è nel profilo gratuito',
      'Rituale quotidiano di check-in di 2 minuti',
      'Rilevamento di schemi e revisioni settimanali',
      'Serie, punteggio e responsabilità gentile',
      'Disponibile in 10 lingue',
    ],
    price_premium_btn: 'Inizia il tuo cammino',
    guarantee: '🛡 Garanzia di rimborso di 30 giorni · Annulli quando vuoi',
    final_1: 'La relazione più onesta che avrai mai',
    final_2: 'è quella con te stesso.',
    footer_text: 'Disponibile in 10 lingue. Fatto per chi ha chiuso con i consigli generici.',
    free_tag: 'Profilo gratuito',
  },

  pt: {
    nav_start: 'Começar',
    banner_back: '✦ Bem-vindo de volta — o teu perfil está à tua espera',
    banner_view: 'Ver o meu perfil →',
    hero_title_1: 'Quando te alinhas contigo,',
    hero_title_2: 'tudo o resto vem por si.',
    hero_sub: 'Human Design. Astrologia. Numerologia. Um perfil que finalmente te diz quem és — e um ritual diário para o viver.',
    hero_cta: 'Começa aqui',
    hero_cta_note: 'Grátis. Sem cartão. 30 segundos.',
    get_title: 'O que realmente recebes',
    get_sub: 'Quatro peças desenhadas para funcionar juntas. Construídas à volta de quem és — não conselhos genéricos.',
    card_profile_tag: 'Perfil',
    card_profile_title: 'O teu perfil único',
    card_profile_text: 'Human Design, astrologia e numerologia sintetizados num documento honesto. Pessoal. Específico. Teu.',
    card_ritual_tag: 'Ritual diário',
    card_ritual_title: 'Ritual diário de 2 minutos',
    card_ritual_text: 'Um check-in curto. Perguntas reais. O teu alinhamento, acompanhado ao longo do tempo sem nunca se tornar uma obrigação.',
    card_patterns_tag: 'Padrões',
    card_patterns_title: 'Padrões que te guiam',
    card_patterns_text: 'Sequências, revisões semanais e deteção de padrões que aprende contigo — não com a ideia de progresso de uma app genérica.',
    card_foundation_tag: 'Fundação',
    card_foundation_title: 'Construído sobre quem és',
    card_foundation_text: 'Três sistemas antigos, calculados a partir dos teus dados de nascimento, tecidos num perfil contemporâneo que podes realmente usar.',
    pillar_astro: 'Astrologia',
    pillar_num: 'Numerologia',
    trust_banner: 'Sem subscrição. Sem cartão. O teu perfil é grátis.',
    trust_private: 'Privado e seguro',
    trust_fast: 'Pronto em 2 minutos',
    trust_langs: '10 idiomas',
    how_title: 'Como funciona',
    step1_title: 'Insere os teus dados de nascimento',
    step1_text: 'Nome, data, hora e cidade de nascimento. É assim que o teu perfil único é calculado.',
    step2_title: 'Recebe o teu perfil',
    step2_text: 'Em 2-3 minutos, o teu perfil pessoal é gerado — caloroso, honesto e estruturado.',
    step3_title: 'Começa o caminho',
    step3_text: 'Lê o teu perfil. Inicia o teu plano. Faz check-in diariamente. O resto desenrola-se a partir daí.',
    pricing_title: 'Preços claros. Sem surpresas.',
    pricing_sub: 'Começa grátis. Avança só se valer a pena.',
    price_free_tag: 'Perfil',
    price_free: 'Grátis',
    price_free_note: 'Teu para sempre',
    price_free_desc: 'O teu perfil pessoal completo — Human Design, astrologia e numerologia combinados num único documento. Inclui o teu plano de alinhamento.',
    price_free_btn: 'Obtém o teu perfil →',
    price_premium_tag: 'O caminho completo',
    price_month: '/mês',
    price_annual: 'ou €80/ano — 2 meses grátis',
    features: [
      'Tudo o que está no perfil gratuito',
      'Ritual diário de check-in de 2 minutos',
      'Deteção de padrões e revisões semanais',
      'Sequências, pontuação e responsabilidade gentil',
      'Disponível em 10 idiomas',
    ],
    price_premium_btn: 'Começa o teu caminho',
    guarantee: '🛡 Garantia de devolução de 30 dias · Cancela quando quiseres',
    final_1: 'A relação mais honesta que alguma vez terás',
    final_2: 'é a que tens contigo.',
    footer_text: 'Disponível em 10 idiomas. Feito para quem se cansou de conselhos genéricos.',
    free_tag: 'Perfil gratuito',
  },

  nl: {
    nav_start: 'Start',
    banner_back: '✦ Welkom terug — je profiel wacht op je',
    banner_view: 'Bekijk mijn profiel →',
    hero_title_1: 'Als je je met jezelf uitlijnt,',
    hero_title_2: 'volgt de rest vanzelf.',
    hero_sub: 'Human Design. Astrologie. Numerologie. Eén profiel dat je eindelijk vertelt wie je bent — en een dagelijks ritueel om het te leven.',
    hero_cta: 'Begin hier',
    hero_cta_note: 'Gratis. Geen kaart. 30 seconden.',
    get_title: 'Wat je echt krijgt',
    get_sub: 'Vier onderdelen, ontworpen om samen te werken. Gebouwd rond wie je bent — geen generiek advies.',
    card_profile_tag: 'Profiel',
    card_profile_title: 'Jouw unieke profiel',
    card_profile_text: 'Human Design, astrologie en numerologie samengebracht in één eerlijk document. Persoonlijk. Specifiek. Van jou.',
    card_ritual_tag: 'Dagelijks ritueel',
    card_ritual_title: 'Dagelijks ritueel van 2 minuten',
    card_ritual_text: 'Een korte check-in. Echte vragen. Je uitlijning, gevolgd in de tijd zonder ooit een klus te worden.',
    card_patterns_tag: 'Patronen',
    card_patterns_title: 'Patronen die je leiden',
    card_patterns_text: 'Streaks, wekelijkse terugblikken en patroonherkenning die van jou leert — niet van het vooruitgangsidee van een generieke app.',
    card_foundation_tag: 'Fundament',
    card_foundation_title: 'Gebouwd op wie je bent',
    card_foundation_text: 'Drie oude systemen, berekend uit je geboortegegevens, verweven tot een eigentijds profiel dat je echt kunt gebruiken.',
    pillar_astro: 'Astrologie',
    pillar_num: 'Numerologie',
    trust_banner: 'Geen abonnement. Geen kaart. Je profiel is gratis.',
    trust_private: 'Privé en veilig',
    trust_fast: 'Klaar in 2 minuten',
    trust_langs: '10 talen',
    how_title: 'Hoe het werkt',
    step1_title: 'Voer je geboortegegevens in',
    step1_text: 'Naam, datum, tijd en geboortestad. Zo wordt je unieke profiel berekend.',
    step2_title: 'Ontvang je profiel',
    step2_text: 'In 2-3 minuten wordt je persoonlijke profiel gegenereerd — warm, eerlijk en gestructureerd.',
    step3_title: 'Begin de weg',
    step3_text: 'Lees je profiel. Start je plan. Doe dagelijks je check-in. De rest ontvouwt zich vanzelf.',
    pricing_title: 'Duidelijke prijzen. Geen verrassingen.',
    pricing_sub: 'Begin gratis. Upgrade alleen als het de moeite waard is.',
    price_free_tag: 'Profiel',
    price_free: 'Gratis',
    price_free_note: 'Voor altijd van jou',
    price_free_desc: 'Je volledige persoonlijke profiel — Human Design, astrologie en numerologie gecombineerd in één document. Inclusief je uitlijningsplan.',
    price_free_btn: 'Krijg je profiel →',
    price_premium_tag: 'De volledige weg',
    price_month: '/maand',
    price_annual: 'of €80/jaar — 2 maanden gratis',
    features: [
      'Alles uit het gratis profiel',
      'Dagelijks check-in-ritueel van 2 minuten',
      'Patroonherkenning en wekelijkse terugblikken',
      'Streaks, score en zachte verantwoordelijkheid',
      'Beschikbaar in 10 talen',
    ],
    price_premium_btn: 'Begin jouw weg',
    guarantee: '🛡 30 dagen geld-terug-garantie · Altijd opzegbaar',
    final_1: 'De eerlijkste relatie die je ooit zult hebben',
    final_2: 'is die met jezelf.',
    footer_text: 'Beschikbaar in 10 talen. Gemaakt voor mensen die klaar zijn met generiek advies.',
    free_tag: 'Gratis profiel',
  },

  pl: {
    nav_start: 'Start',
    banner_back: '✦ Witaj z powrotem — twój profil czeka',
    banner_view: 'Zobacz mój profil →',
    hero_title_1: 'Kiedy wyrównasz się ze sobą,',
    hero_title_2: 'reszta przychodzi sama.',
    hero_sub: 'Human Design. Astrologia. Numerologia. Jeden profil, który wreszcie mówi ci, kim jesteś — i codzienny rytuał, by tym żyć.',
    hero_cta: 'Zacznij tutaj',
    hero_cta_note: 'Za darmo. Bez karty. 30 sekund.',
    get_title: 'Co naprawdę otrzymujesz',
    get_sub: 'Cztery elementy zaprojektowane, by działać razem. Zbudowane wokół tego, kim jesteś — nie ogólnych porad.',
    card_profile_tag: 'Profil',
    card_profile_title: 'Twój unikalny profil',
    card_profile_text: 'Human Design, astrologia i numerologia połączone w jeden szczery dokument. Osobisty. Konkretny. Twój.',
    card_ritual_tag: 'Codzienny rytuał',
    card_ritual_title: '2-minutowy codzienny rytuał',
    card_ritual_text: 'Krótki check-in. Prawdziwe pytania. Twoje wyrównanie, śledzone w czasie, bez poczucia przykrego obowiązku.',
    card_patterns_tag: 'Wzorce',
    card_patterns_title: 'Wzorce, które cię prowadzą',
    card_patterns_text: 'Serie, cotygodniowe przeglądy i wykrywanie wzorców, które uczy się od ciebie — nie od wyobrażenia o postępie generycznej aplikacji.',
    card_foundation_tag: 'Fundament',
    card_foundation_title: 'Zbudowany na tym, kim jesteś',
    card_foundation_text: 'Trzy dawne systemy, obliczone z twoich danych urodzenia, utkane we współczesny profil, którego naprawdę możesz używać.',
    pillar_astro: 'Astrologia',
    pillar_num: 'Numerologia',
    trust_banner: 'Bez subskrypcji. Bez karty. Twój profil jest darmowy.',
    trust_private: 'Prywatne i bezpieczne',
    trust_fast: 'Gotowe w 2 minuty',
    trust_langs: '10 języków',
    how_title: 'Jak to działa',
    step1_title: 'Wprowadź dane urodzenia',
    step1_text: 'Imię, data, godzina i miasto urodzenia. Tak obliczany jest twój unikalny profil.',
    step2_title: 'Otrzymaj swój profil',
    step2_text: 'W 2-3 minuty twój osobisty profil zostaje wygenerowany — ciepły, szczery i uporządkowany.',
    step3_title: 'Zacznij drogę',
    step3_text: 'Przeczytaj swój profil. Uruchom plan. Rób codzienny check-in. Reszta rozwinie się stamtąd.',
    pricing_title: 'Jasne ceny. Bez niespodzianek.',
    pricing_sub: 'Zacznij za darmo. Przejdź dalej tylko jeśli warto.',
    price_free_tag: 'Profil',
    price_free: 'Za darmo',
    price_free_note: 'Twój na zawsze',
    price_free_desc: 'Twój pełny osobisty profil — Human Design, astrologia i numerologia połączone w jednym dokumencie. Zawiera twój plan wyrównania.',
    price_free_btn: 'Odbierz swój profil →',
    price_premium_tag: 'Pełna droga',
    price_month: '/miesiąc',
    price_annual: 'lub €80/rok — 2 miesiące gratis',
    features: [
      'Wszystko z darmowego profilu',
      'Codzienny 2-minutowy rytuał check-in',
      'Wykrywanie wzorców i cotygodniowe przeglądy',
      'Serie, wynik i łagodna odpowiedzialność',
      'Dostępne w 10 językach',
    ],
    price_premium_btn: 'Zacznij swoją drogę',
    guarantee: '🛡 30-dniowa gwarancja zwrotu pieniędzy · Anuluj w każdej chwili',
    final_1: 'Najszczersza relacja, jaką kiedykolwiek będziesz mieć,',
    final_2: 'to ta z samym sobą.',
    footer_text: 'Dostępne w 10 językach. Dla ludzi, którzy mają dość ogólnych porad.',
    free_tag: 'Darmowy profil',
  },

  hu: {
    nav_start: 'Kezdés',
    banner_back: '✦ Üdv újra — a profilod vár rád',
    banner_view: 'Profilom megtekintése →',
    hero_title_1: 'Amikor összhangba kerülsz önmagaddal,',
    hero_title_2: 'minden más magától jön.',
    hero_sub: 'Human Design. Asztrológia. Numerológia. Egy profil, amely végre megmondja, ki vagy — és egy napi rituálé, hogy ezt élhesd is.',
    hero_cta: 'Kezdd itt',
    hero_cta_note: 'Ingyenes. Kártya nélkül. 30 másodperc.',
    get_title: 'Amit valójában kapsz',
    get_sub: 'Négy elem, amelyek együtt működnek. Arra építve, aki vagy — nem általános tanácsokra.',
    card_profile_tag: 'Profil',
    card_profile_title: 'A te egyedi profilod',
    card_profile_text: 'Human Design, asztrológia és numerológia egyetlen őszinte dokumentumban. Személyes. Konkrét. A tiéd.',
    card_ritual_tag: 'Napi rituálé',
    card_ritual_title: '2 perces napi rituálé',
    card_ritual_text: 'Rövid bejelentkezés. Valódi kérdések. Az összhangod, időben követve, anélkül hogy valaha teherré válna.',
    card_patterns_tag: 'Minták',
    card_patterns_title: 'Minták, amelyek vezetnek',
    card_patterns_text: 'Sorozatok, heti áttekintések és mintafelismerés, amely tőled tanul — nem egy általános app elképzelésétől a fejlődésről.',
    card_foundation_tag: 'Alap',
    card_foundation_title: 'Arra építve, aki vagy',
    card_foundation_text: 'Három ősi rendszer, a születési adataidból kiszámítva, egy kortárs profillá szőve, amelyet tényleg használhatsz.',
    pillar_astro: 'Asztrológia',
    pillar_num: 'Numerológia',
    trust_banner: 'Nincs előfizetés. Nincs kártya. A profilod ingyenes.',
    trust_private: 'Privát és biztonságos',
    trust_fast: '2 perc alatt kész',
    trust_langs: '10 nyelv',
    how_title: 'Hogyan működik',
    step1_title: 'Add meg a születési adataidat',
    step1_text: 'Név, dátum, idő és születési város. Így számítjuk ki az egyedi profilodat.',
    step2_title: 'Megkapod a profilod',
    step2_text: '2-3 perc alatt elkészül a személyes profilod — meleg, őszinte és strukturált.',
    step3_title: 'Kezdd el az utat',
    step3_text: 'Olvasd el a profilod. Indítsd el a terved. Jelentkezz be naponta. A többi onnan bontakozik ki.',
    pricing_title: 'Átlátható árak. Nincsenek meglepetések.',
    pricing_sub: 'Kezdd ingyen. Csak akkor lépj tovább, ha megéri.',
    price_free_tag: 'Profil',
    price_free: 'Ingyenes',
    price_free_note: 'Örökre a tiéd',
    price_free_desc: 'A teljes személyes profilod — Human Design, asztrológia és numerológia egyetlen dokumentumban. Tartalmazza az igazítási tervedet.',
    price_free_btn: 'Kérd a profilod →',
    price_premium_tag: 'A teljes út',
    price_month: '/hónap',
    price_annual: 'vagy €80/év — 2 hónap ajándék',
    features: [
      'Minden az ingyenes profilból',
      'Napi 2 perces bejelentkezési rituálé',
      'Mintafelismerés és heti áttekintések',
      'Sorozatok, pontszám és szelíd elszámoltathatóság',
      'Elérhető 10 nyelven',
    ],
    price_premium_btn: 'Kezdd el az utad',
    guarantee: '🛡 30 napos pénzvisszafizetési garancia · Bármikor lemondható',
    final_1: 'A legőszintébb kapcsolat, amid valaha lesz,',
    final_2: 'az önmagaddal való.',
    footer_text: 'Elérhető 10 nyelven. Azoknak, akik végeztek az általános tanácsokkal.',
    free_tag: 'Ingyenes profil',
  },
}

export function lt(language, key) {
  const lang = LANDING[language] || LANDING['en']
  return lang[key] !== undefined ? lang[key] : (LANDING['en'][key] !== undefined ? LANDING['en'][key] : key)
}