// 25.07 seara: extras din app/subscribe/page.js ca sa poata fi testat direct
// din scripts/test-subscribe-copy.mjs (page.js are JSX, nu poate fi importat
// direct intr-un script Node simplu).
export const SUBSCRIBE_LABELS = {
  en: {
    back: '← Back',
    title_line1: "We're accountable to everyone.",
    title_line2: 'Except ourselves.',
    bridge: 'Here, the commitment is with yourself. We just keep it alive — day by day.',
    subtitle: "Two quiet moments a day. In the evening you leave the day in the water and set an intention for tomorrow; in the morning, it finds you.",
    offer_text: 'The first 1,000 people get the full profile, free. After that, the profile is €4. {n} left.',
    monthly: 'Monthly',
    annual: 'Yearly — two months free',
    period_month: '/month',
    period_year: '/year',
    features: [
      'Two rituals a day, under a minute each',
      'The daily thought, written from your profile',
      'The Patterns mirror — what keeps returning in what you write',
      'The Week, Seen — every Saturday',
      'Your presence, held gently, no scores',
      'Your personal year phase, always in context',
      'All of it, in 11 languages',
    ],
    subscribe_prefix: 'Start',
    redirecting: 'Redirecting...',
    guarantee_line: 'Your money back in the first 30 days, no questions asked. Cancel in one click.',
    try_free: 'Try for free first →',
    no_profile_text: "Don't have your free profile yet?",
    no_profile_link: 'Generate your free profile first →',
    promise_title: 'Our promise to you',
    promise_1_title: 'Your money back in 30 days',
    promise_1_text: "If it didn't serve you, we refund you in full. No questions asked.",
    promise_2_title: 'Leave whenever you want',
    promise_2_text: 'Cancel in one click, from the app. What you wrote stays yours.',
    promise_3_title: 'Written from your data',
    promise_3_text: 'Every text you read is generated from your profile, not from a template.',
    already_title: "You're already in.",
    already_text: 'Your subscription is active — everything here is already yours.',
    already_link: 'Go to Today →',
  },
  ro: {
    back: '← Înapoi',
    title_line1: 'Suntem responsabili față de toți.',
    title_line2: 'Mai puțin față de noi.',
    bridge: 'Aici, angajamentul e cu tine. Noi doar îl ținem viu — zi de zi.',
    subtitle: 'Două momente de liniște pe zi. Seara lași ziua în apă și semeni o intenție pentru mâine; dimineața te așteaptă.',
    offer_text: 'Primii 1.000 de oameni primesc profilul complet, gratuit. După ei, profilul e €4. Au mai rămas {n}.',
    monthly: 'Lunar',
    annual: 'Anual — două luni gratuite',
    period_month: ' pe lună',
    period_year: ' pe an',
    features: [
      'Două ritualuri pe zi, sub un minut fiecare',
      'Gândul zilei, scris din profilul tău',
      'Oglinda Tiparelor — ce se repetă în ce scrii',
      'Privirea săptămânii, sâmbăta',
      'Prezența ta, ținută blând, fără scoruri',
      'Faza anului tău personal, mereu în context',
      'Totul, în 11 limbi',
    ],
    subscribe_prefix: 'Începe',
    redirecting: 'Redirecționare...',
    guarantee_line: 'Banii înapoi în primele 30 de zile, fără să întrebăm de ce. Anulezi dintr-un click.',
    try_free: 'Încearcă gratuit mai întâi →',
    no_profile_text: 'Nu ai încă profilul gratuit?',
    no_profile_link: 'Generează-ți profilul gratuit mai întâi →',
    promise_title: 'Promisiunea noastră pentru tine',
    promise_1_title: 'Banii înapoi în 30 de zile',
    promise_1_text: 'Dacă nu ți-a folosit, îți returnăm banii integral. Fără să întrebăm de ce.',
    promise_2_title: 'Pleci când vrei',
    promise_2_text: 'Anulezi dintr-un click, din aplicație. Ce ai scris rămâne al tău.',
    promise_3_title: 'Scris din datele tale',
    promise_3_text: 'Fiecare text pe care îl citești e generat din profilul tău, nu dintr-un șablon.',
    already_title: 'Ești deja înăuntru.',
    already_text: 'Abonamentul tău e activ — tot ce e aici e deja al tău.',
    already_link: 'Mergi la Azi →',
  },
  es: {
    back: '← Atrás',
    title_line1: 'Somos responsables ante todos.',
    title_line2: 'Menos ante nosotros mismos.',
    bridge: 'Aquí, el compromiso es contigo mismo. Nosotros solo lo mantenemos vivo — día a día.',
    subtitle: 'Dos momentos de calma al día. Por la noche dejas el día en el agua y siembras una intención para mañana; por la mañana, te encuentra.',
    offer_text: 'Las primeras 1.000 personas reciben el perfil completo, gratis. Después, el perfil cuesta 4 €. Quedan {n}.',
    monthly: 'Mensual',
    annual: 'Anual — dos meses gratis',
    period_month: ' al mes',
    period_year: ' al año',
    features: [
      'Dos rituales al día, menos de un minuto cada uno',
      'El pensamiento del día, escrito desde tu perfil',
      'El espejo de Patrones — lo que se repite en lo que escribes',
      'La Semana, Vista — cada sábado',
      'Tu presencia, sostenida con suavidad, sin puntuaciones',
      'La fase de tu año personal, siempre en contexto',
      'Todo, en 11 idiomas',
    ],
    subscribe_prefix: 'Empezar',
    redirecting: 'Redirigiendo...',
    guarantee_line: 'Tu dinero de vuelta en los primeros 30 días, sin preguntas. Cancela con un clic.',
    try_free: 'Probar gratis primero →',
    no_profile_text: '¿Aún no tienes tu perfil gratuito?',
    no_profile_link: 'Genera tu perfil gratuito primero →',
    promise_title: 'Nuestra promesa para ti',
    promise_1_title: 'Tu dinero de vuelta en 30 días',
    promise_1_text: 'Si no te sirvió, te devolvemos todo. Sin preguntas.',
    promise_2_title: 'Te vas cuando quieras',
    promise_2_text: 'Cancelas con un clic, desde la app. Lo que escribiste sigue siendo tuyo.',
    promise_3_title: 'Escrito a partir de tus datos',
    promise_3_text: 'Cada texto que lees se genera desde tu perfil, no desde una plantilla.',
    already_title: 'Ya estás dentro.',
    already_text: 'Tu suscripción está activa — todo esto ya es tuyo.',
    already_link: 'Ir a Hoy →',
  },
  fr: {
    back: '← Retour',
    title_line1: 'Nous sommes responsables envers tout le monde.',
    title_line2: 'Sauf envers nous-mêmes.',
    bridge: "Ici, l'engagement est envers toi-même. Nous, on le garde simplement vivant — jour après jour.",
    subtitle: "Deux moments de calme par jour. Le soir, tu laisses la journée dans l'eau et sèmes une intention pour demain ; le matin, elle te retrouve.",
    offer_text: 'Les 1 000 premières personnes reçoivent le profil complet, gratuitement. Ensuite, le profil coûte 4 €. Il en reste {n}.',
    monthly: 'Mensuel',
    annual: 'Annuel — deux mois offerts',
    period_month: ' par mois',
    period_year: ' par an',
    features: [
      "Deux rituels par jour, moins d'une minute chacun",
      'La pensée du jour, écrite à partir de ton profil',
      'Le miroir des Tendances — ce qui revient dans ce que tu écris',
      'La Semaine, Vue — chaque samedi',
      'Ta présence, tenue avec douceur, sans scores',
      'La phase de ton année personnelle, toujours en contexte',
      'Le tout, en 11 langues',
    ],
    subscribe_prefix: 'Commencer',
    redirecting: 'Redirection...',
    guarantee_line: 'Argent remboursé dans les 30 premiers jours, sans questions. Annule en un clic.',
    try_free: "Essayer gratuitement d'abord →",
    no_profile_text: "Tu n'as pas encore ton profil gratuit ?",
    no_profile_link: "Génère d'abord ton profil gratuit →",
    promise_title: 'Notre promesse envers toi',
    promise_1_title: 'Ton argent remboursé en 30 jours',
    promise_1_text: "Si ça ne t'a pas aidé, on te rembourse intégralement. Sans questions.",
    promise_2_title: 'Tu pars quand tu veux',
    promise_2_text: "Tu annules en un clic, depuis l'appli. Ce que tu as écrit reste à toi.",
    promise_3_title: 'Écrit à partir de tes données',
    promise_3_text: "Chaque texte que tu lis est généré à partir de ton profil, pas d'un modèle.",
    already_title: 'Tu es déjà dedans.',
    already_text: 'Ton abonnement est actif — tout ça est déjà à toi.',
    already_link: "Aller à Aujourd'hui →",
  },
  de: {
    back: '← Zurück',
    title_line1: 'Wir sind allen gegenüber verantwortlich.',
    title_line2: 'Nur uns selbst gegenüber nicht.',
    bridge: 'Hier geht die Verpflichtung an dich selbst. Wir halten sie nur lebendig — Tag für Tag.',
    subtitle: 'Zwei ruhige Momente am Tag. Abends lässt du den Tag im Wasser zurück und pflanzt eine Absicht für morgen; am Morgen findet sie dich.',
    offer_text: 'Die ersten 1.000 Menschen erhalten das vollständige Profil kostenlos. Danach kostet das Profil 4 €. Noch {n} übrig.',
    monthly: 'Monatlich',
    annual: 'Jährlich — zwei Monate gratis',
    period_month: ' im Monat',
    period_year: ' im Jahr',
    features: [
      'Zwei Rituale am Tag, jeweils unter einer Minute',
      'Der Gedanke des Tages, geschrieben aus deinem Profil',
      'Der Muster-Spiegel — was sich in dem wiederholt, was du schreibst',
      'Die Woche, gesehen — jeden Samstag',
      'Deine Präsenz, sanft gehalten, ohne Punktzahlen',
      'Die Phase deines persönlichen Jahres, immer im Kontext',
      'Alles, in 11 Sprachen',
    ],
    subscribe_prefix: 'Starten',
    redirecting: 'Weiterleitung...',
    guarantee_line: 'Geld zurück in den ersten 30 Tagen, ohne Nachfragen. Kündige mit einem Klick.',
    try_free: 'Erst kostenlos testen →',
    no_profile_text: 'Hast du dein kostenloses Profil noch nicht?',
    no_profile_link: 'Erstelle zuerst dein kostenloses Profil →',
    promise_title: 'Unser Versprechen an dich',
    promise_1_title: 'Dein Geld zurück in 30 Tagen',
    promise_1_text: 'Wenn es dir nicht geholfen hat, erstatten wir alles zurück. Ohne Nachfragen.',
    promise_2_title: 'Geh, wann du willst',
    promise_2_text: 'Kündige mit einem Klick, direkt in der App. Was du geschrieben hast, bleibt dein Eigentum.',
    promise_3_title: 'Geschrieben aus deinen Daten',
    promise_3_text: 'Jeder Text, den du liest, entsteht aus deinem Profil, nicht aus einer Vorlage.',
    already_title: 'Du bist schon dabei.',
    already_text: 'Dein Abo ist aktiv — das alles gehört bereits dir.',
    already_link: 'Zu Heute →',
  },
  it: {
    back: '← Indietro',
    title_line1: 'Siamo responsabili verso tutti.',
    title_line2: 'Tranne che verso noi stessi.',
    bridge: "Qui, l'impegno è con te stesso. Noi lo teniamo solo vivo — giorno dopo giorno.",
    subtitle: "Due momenti di calma al giorno. La sera lasci la giornata nell'acqua e semini un'intenzione per domani; al mattino, ti ritrova.",
    offer_text: 'Le prime 1.000 persone ricevono il profilo completo, gratis. Dopo, il profilo costa 4 €. Ne restano {n}.',
    monthly: 'Mensile',
    annual: 'Annuale — due mesi gratis',
    period_month: ' al mese',
    period_year: " all'anno",
    features: [
      'Due rituali al giorno, meno di un minuto ciascuno',
      'Il pensiero del giorno, scritto dal tuo profilo',
      'Lo specchio dei Modelli — cosa si ripete in ciò che scrivi',
      'La Settimana, Vista — ogni sabato',
      'La tua presenza, tenuta con delicatezza, senza punteggi',
      'La fase del tuo anno personale, sempre nel contesto',
      'Tutto, in 11 lingue',
    ],
    subscribe_prefix: 'Inizia',
    redirecting: 'Reindirizzamento...',
    guarantee_line: 'Soldi indietro nei primi 30 giorni, senza domande. Annulli con un clic.',
    try_free: 'Prova prima gratis →',
    no_profile_text: 'Non hai ancora il tuo profilo gratuito?',
    no_profile_link: 'Genera prima il tuo profilo gratuito →',
    promise_title: 'La nostra promessa per te',
    promise_1_title: 'Soldi indietro in 30 giorni',
    promise_1_text: 'Se non ti è servito, ti rimborsiamo per intero. Senza domande.',
    promise_2_title: 'Te ne vai quando vuoi',
    promise_2_text: "Annulli con un clic, dall'app. Quello che hai scritto resta tuo.",
    promise_3_title: 'Scritto dai tuoi dati',
    promise_3_text: 'Ogni testo che leggi è generato dal tuo profilo, non da un modello.',
    already_title: 'Sei già dentro.',
    already_text: 'Il tuo abbonamento è attivo — tutto questo è già tuo.',
    already_link: 'Vai a Oggi →',
  },
  pt: {
    back: '← Voltar',
    title_line1: 'Somos responsáveis perante todos.',
    title_line2: 'Exceto perante nós próprios.',
    bridge: 'Aqui, o compromisso é contigo. Nós só o mantemos vivo — dia após dia.',
    subtitle: 'Dois momentos de calma por dia. À noite deixas o dia na água e semeias uma intenção para amanhã; de manhã, ela encontra-te.',
    offer_text: 'As primeiras 1.000 pessoas recebem o perfil completo, grátis. Depois, o perfil custa 4 €. Restam {n}.',
    monthly: 'Mensal',
    annual: 'Anual — dois meses grátis',
    period_month: ' por mês',
    period_year: ' por ano',
    features: [
      'Dois rituais por dia, menos de um minuto cada',
      'O pensamento do dia, escrito a partir do teu perfil',
      'O espelho de Padrões — o que se repete no que escreves',
      'A Semana, Vista — todos os sábados',
      'A tua presença, sustentada com suavidade, sem pontuações',
      'A fase do teu ano pessoal, sempre em contexto',
      'Tudo, em 11 idiomas',
    ],
    subscribe_prefix: 'Começar',
    redirecting: 'A redirecionar...',
    guarantee_line: 'O teu dinheiro de volta nos primeiros 30 dias, sem perguntas. Cancelas num clique.',
    try_free: 'Experimentar grátis primeiro →',
    no_profile_text: 'Ainda não tens o teu perfil gratuito?',
    no_profile_link: 'Gera primeiro o teu perfil gratuito →',
    promise_title: 'A nossa promessa para ti',
    promise_1_title: 'O teu dinheiro de volta em 30 dias',
    promise_1_text: 'Se não te serviu, devolvemos-te tudo. Sem perguntas.',
    promise_2_title: 'Sais quando quiseres',
    promise_2_text: 'Cancelas num clique, a partir da app. O que escreveste continua teu.',
    promise_3_title: 'Escrito a partir dos teus dados',
    promise_3_text: 'Cada texto que lês é gerado a partir do teu perfil, não de um modelo.',
    already_title: 'Já estás dentro.',
    already_text: 'A tua assinatura está ativa — tudo isto já é teu.',
    already_link: 'Ir para Hoje →',
  },
  nl: {
    back: '← Terug',
    title_line1: 'We zijn verantwoording verschuldigd aan iedereen.',
    title_line2: 'Behalve aan onszelf.',
    bridge: 'Hier ligt de verbintenis bij jezelf. Wij houden hem alleen levend — dag na dag.',
    subtitle: "Twee rustige momenten per dag. 's Avonds laat je de dag in het water achter en zaai je een intentie voor morgen; 's ochtends vindt ze je.",
    offer_text: 'De eerste 1.000 mensen krijgen het volledige profiel gratis. Daarna kost het profiel €4. Nog {n} over.',
    monthly: 'Maandelijks',
    annual: 'Jaarlijks — twee maanden gratis',
    period_month: ' per maand',
    period_year: ' per jaar',
    features: [
      'Twee rituelen per dag, elk minder dan een minuut',
      'De dagelijkse gedachte, geschreven vanuit jouw profiel',
      'De Patronenspiegel — wat terugkeert in wat je schrijft',
      'De Week, Gezien — elke zaterdag',
      'Jouw aanwezigheid, zacht vastgehouden, zonder scores',
      'De fase van jouw persoonlijke jaar, altijd in context',
      'Alles, in 11 talen',
    ],
    subscribe_prefix: 'Beginnen',
    redirecting: 'Doorverwijzen...',
    guarantee_line: 'Je geld terug binnen de eerste 30 dagen, zonder vragen. Opzeggen met één klik.',
    try_free: 'Eerst gratis proberen →',
    no_profile_text: 'Heb je je gratis profiel nog niet?',
    no_profile_link: 'Genereer eerst je gratis profiel →',
    promise_title: 'Onze belofte aan jou',
    promise_1_title: 'Je geld terug binnen 30 dagen',
    promise_1_text: 'Als het niet voor je werkte, betalen we alles terug. Zonder vragen.',
    promise_2_title: 'Vertrek wanneer je wilt',
    promise_2_text: 'Je zegt op met één klik, vanuit de app. Wat je schreef, blijft van jou.',
    promise_3_title: 'Geschreven vanuit jouw gegevens',
    promise_3_text: 'Elke tekst die je leest, komt uit jouw profiel, niet uit een sjabloon.',
    already_title: 'Je bent er al bij.',
    already_text: 'Je abonnement is actief — dit alles is al van jou.',
    already_link: 'Naar Vandaag →',
  },
  pl: {
    back: '← Wstecz',
    title_line1: 'Jesteśmy odpowiedzialni przed wszystkimi.',
    title_line2: 'Poza sobą samymi.',
    bridge: 'Tutaj zobowiązanie jest wobec siebie samego. My tylko podtrzymujemy je przy życiu — dzień po dniu.',
    subtitle: 'Dwie ciche chwile dziennie. Wieczorem zostawiasz dzień w wodzie i zasiewasz intencję na jutro; rano ona cię odnajduje.',
    offer_text: 'Pierwsze 1000 osób otrzymuje pełny profil za darmo. Potem profil kosztuje 4 €. Zostało {n}.',
    monthly: 'Miesięcznie',
    annual: 'Rocznie — dwa miesiące gratis',
    period_month: ' miesięcznie',
    period_year: ' rocznie',
    features: [
      'Dwa rytuały dziennie, każdy poniżej minuty',
      'Myśl dnia, napisana na podstawie twojego profilu',
      'Lustro Wzorców — co się powtarza w tym, co piszesz',
      'Tydzień, Zobaczony — w każdą sobotę',
      'Twoja obecność, trzymana łagodnie, bez wyników',
      'Faza twojego roku osobistego, zawsze w kontekście',
      'Wszystko, w 11 językach',
    ],
    subscribe_prefix: 'Zacznij',
    redirecting: 'Przekierowanie...',
    guarantee_line: 'Zwrot pieniędzy w ciągu pierwszych 30 dni, bez pytań. Anulujesz jednym kliknięciem.',
    try_free: 'Najpierw wypróbuj za darmo →',
    no_profile_text: 'Nie masz jeszcze swojego darmowego profilu?',
    no_profile_link: 'Najpierw wygeneruj swój darmowy profil →',
    promise_title: 'Nasza obietnica dla ciebie',
    promise_1_title: 'Zwrot pieniędzy w 30 dni',
    promise_1_text: 'Jeśli ci to nie pomogło, zwracamy całość. Bez pytań.',
    promise_2_title: 'Odchodzisz, kiedy chcesz',
    promise_2_text: 'Anulujesz jednym kliknięciem, z aplikacji. To, co napisałeś, zostaje twoje.',
    promise_3_title: 'Napisane z twoich danych',
    promise_3_text: 'Każdy tekst, który czytasz, powstaje z twojego profilu, nie z szablonu.',
    already_title: 'Już jesteś w środku.',
    already_text: 'Twoja subskrypcja jest aktywna — to wszystko już jest twoje.',
    already_link: 'Przejdź do Dziś →',
  },
  hu: {
    back: '← Vissza',
    title_line1: 'Mindenkinek felelősséggel tartozunk.',
    title_line2: 'Csak magunknak nem.',
    bridge: 'Itt az elköteleződés önmagaddal van. Mi csak életben tartjuk — napról napra.',
    subtitle: 'Két csendes pillanat naponta. Este a vízben hagyod a napot, és szándékot vetsz a holnapra; reggel az megtalál téged.',
    offer_text: 'Az első 1000 ember ingyen kapja meg a teljes profilt. Utána a profil 4 € lesz. Még {n} maradt.',
    monthly: 'Havonta',
    annual: 'Évente — két hónap ingyen',
    period_month: ' havonta',
    period_year: ' évente',
    features: [
      'Két rituálé naponta, egyenként egy percnél rövidebb',
      'A napi gondolat, a profilodból írva',
      'A Minták tükre — ami visszatér abban, amit írsz',
      'A Hét, Megmutatva — minden szombaton',
      'A jelenléted, gyengéden tartva, pontszámok nélkül',
      'A személyes éved fázisa, mindig kontextusban',
      'Minden, 11 nyelven',
    ],
    subscribe_prefix: 'Kezdés',
    redirecting: 'Átirányítás...',
    guarantee_line: 'Pénzvisszatérítés az első 30 napban, kérdés nélkül. Egy kattintással lemondhatod.',
    try_free: 'Előbb ingyen kipróbálom →',
    no_profile_text: 'Még nincs meg az ingyenes profilod?',
    no_profile_link: 'Először generáld le az ingyenes profilodat →',
    promise_title: 'Az ígéretünk neked',
    promise_1_title: 'Pénzed vissza 30 napon belül',
    promise_1_text: 'Ha nem vált be, teljes összeget visszatérítünk. Kérdés nélkül.',
    promise_2_title: 'Akkor mész el, amikor akarod',
    promise_2_text: 'Egy kattintással lemondod, az alkalmazásból. Amit írtál, a tiéd marad.',
    promise_3_title: 'A saját adataidból írva',
    promise_3_text: 'Minden szöveg, amit olvasol, a profilodból készül, nem sablonból.',
    already_title: 'Már bent vagy.',
    already_text: 'Az előfizetésed aktív — mindez már a tiéd.',
    already_link: 'Ugrás a Mához →',
  },
  ru: {
    back: '← Назад',
    title_line1: 'Мы отвечаем перед всеми.',
    title_line2: 'Кроме самих себя.',
    bridge: 'Здесь обязательство — перед самим собой. Мы просто поддерживаем его — день за днём.',
    subtitle: 'Два спокойных момента в день. Вечером ты оставляешь день в воде и сеешь намерение на завтра; утром оно находит тебя.',
    offer_text: 'Первые 1000 человек получают полный профиль бесплатно. После этого профиль стоит 4 €. Осталось {n}.',
    monthly: 'Ежемесячно',
    annual: 'Ежегодно — два месяца бесплатно',
    period_month: ' в месяц',
    period_year: ' в год',
    features: [
      'Два ритуала в день, меньше минуты каждый',
      'Мысль дня, написанная на основе твоего профиля',
      'Зеркало Закономерностей — что повторяется в том, что ты пишешь',
      'Неделя, Увиденная — каждую субботу',
      'Твоё присутствие, удерживаемое бережно, без баллов',
      'Фаза твоего личного года, всегда в контексте',
      'Всё это, на 11 языках',
    ],
    subscribe_prefix: 'Начать',
    redirecting: 'Перенаправление...',
    guarantee_line: 'Возврат денег в первые 30 дней, без вопросов. Отменяешь в один клик.',
    try_free: 'Сначала попробовать бесплатно →',
    no_profile_text: 'Ещё нет бесплатного профиля?',
    no_profile_link: 'Сначала создать бесплатный профиль →',
    promise_title: 'Наше обещание тебе',
    promise_1_title: 'Деньги назад за 30 дней',
    promise_1_text: 'Если тебе не помогло, мы вернём всё полностью. Без вопросов.',
    promise_2_title: 'Уходишь, когда захочешь',
    promise_2_text: 'Отменяешь в один клик, прямо в приложении. То, что ты написал, остаётся твоим.',
    promise_3_title: 'Написано из твоих данных',
    promise_3_text: 'Каждый текст, который ты читаешь, создаётся из твоего профиля, а не из шаблона.',
    already_title: 'Ты уже внутри.',
    already_text: 'Твоя подписка активна — всё это уже твоё.',
    already_link: 'Перейти к Сегодня →',
  },
}
